window.OET_WORDS = [
  "Constant",
  "Fish oil",
  "Gardener",
  "Metallic taste",
  "Cystoscopy",
  "Transplant",
  "Yoga",
  "Mood swings",
  "Dark red urine",
  "Lack of energy",
  "High blood pressure",
  "Itching",
  "Pregnancy",
  "Cramps",
  "Thick mucus",
  "Tenderness",
  "Postnasal drip",
  "Jaw",
  "Nosebleed",
  "Snoring",
  "Surveyor",
  "Socialising",
  "Sternum",
  "Crohn's disease",
  "High arches",
  "Insoles",
  "Osteoarthritis",
  "Tramadol injections",
  "Aerobic exercises",
  "Ice packs",
  "Numbness",
  "Poor circulation",
  "Grip",
  "Freelance typing",
  "Wrist",
  "Nebuliser",
  "Menthol oil",
  "Lumbar puncture",
  "Referral to physiotherapist",
  "Dengue fever",
  "First visit",
  "Trip",
  "Backpack trip",
  "Mononucleosis",
  "Loss of libido",
  "Sleepiness",
  "Sleep",
  "Tired",
  "Autoimmune disease",
  "Varicella",
  "Herpes zoster",
  "Multiple sclerosis",
  "Balance",
  "Soles",
  "Scalp",
  "Diabetes",
  "Chef",
  "Corticosteroid cream",
  "Gym",
  "Carer",
  "Elbow creases",
  "Prostate enlargement",
  "Hairdresser",
  "Hysterectomy",
  "Fluids",
  "Conjunctivitis",
  "Vision",
  "Tendinitis",
  "Soap",
  "Head",
  "Chin",
  "Jaundice",
  "Blood pressure",
  "Gallstone",
  "Shoulder",
  "Bile duct",
  "Fat reduction",
  "Piercing",
  "Anxiety",
  "Nerve block injections",
  "Badminton",
  "Translator",
  "Cholesterol",
  "Prostate cancer",
  "Lethargy",
  "Strong smells",
  "Stiff neck",
  "Vomiting attacks",
  "Achilles tendon",
  "Red meat",
  "Acupuncture",
  "Concussion",
  "Glandular fever",
  "B12 deficiency",
  "Mini stroke",
  "Angina",
  "Skin rashes",
  "Joint pain",
  "Around ribs",
  "Anti blockers",
  "Heparin injection",
  "Antisocial",
  "Financial difficulties",
  "Gastric bypass",
  "Lethargic",
  "Self-confidence",
  "Cold compress",
  "Gout",
  "Nausea",
  "Colchicine",
  "Knee",
  "Paddle",
  "Incoherent",
  "Stumble",
  "Daughters",
  "Clammy",
  "Clicking",
  "Stress",
  "Infertility",
  "Steroids",
  "PICC line",
  "Constricted veins",
  "Lawyer",
  "Dizzy",
  "Lower back",
  "Emotional changes",
  "Laughing",
  "Stroke",
  "High fat",
  "Weight",
  "Apathy",
  "Rash",
  "Left knee",
  "Counsellor",
  "Alcohol dependence",
  "Glass factory",
  "Sepsis",
  "Dysphagia",
  "Confusion",
  "Urine retention",
  "Sputum",
  "Shingles",
  "Septicaemia",
  "IBS",
  "Burning",
  "Elastic bandages",
  "Anti-inflammatories",
  "Allopurinol",
  "Gallbladder stones",
  "Skinny",
  "Rubbery",
  "Hotel manager",
  "Radical hysterectomy",
  "Cellulitis",
  "Water pills",
  "Hips",
  "Repetitive strain injury",
  "Exhausted",
  "Omega-3",
  "Twinges",
  "Fatty meat",
  "Rotator cuff tear",
  "Frozen shoulder",
  "Raise arm",
  "Gastric balloon",
  "Excruciating",
  "Walking frame",
  "Vitamin D",
  "Compartment syndrome",
  "Heels",
  "Bruising",
  "Infection",
  "Steroid injections",
  "Thigh",
  "Deep vein thrombosis",
  "Atrial fibrillation",
  "Chills",
  "Discharge",
  "Gluten",
  "Hay fever",
  "Antifungal",
  "Sinus infection",
  "Antibiotics",
  "Antihistamines",
  "Pancreatitis",
  "Vomiting",
  "Seizure",
  "Dribbling",
  "Salads",
  "Finance",
  "Psychological",
  "A chair",
  "Life-threatening",
  "Bouts of vomiting",
  "Echocardiogram",
  "Flu",
  "Financial consultant",
  "Onion",
  "Antidepressants",
  "Hiatus hernia",
  "Jogging",
  "Long journey",
  "Ventricle",
  "Weakness",
  "Overactive thyroid",
  "Sleep apnoea",
  "Vegan",
  "Left leg",
  "Septic shock",
  "Statin",
  "Bearable",
  "Bank manager",
  "Neck",
  "Rheumatoid arthritis",
  "Aneurysm",
  "Co-codamol",
  "Buttocks",
  "Hot shower",
  "Van driver",
  "Sailing",
  "Left side",
  "Club",
  "Corticosteroids",
  "Flash",
  "Lithium",
  "Oxygen therapy",
  "Cluster headache",
  "Double vision",
  "Cardiac",
  "Left thigh",
  "Palpitations",
  "Heartburn",
  "Nuts",
  "Dental hygiene",
  "Needle biopsy",
  "Hypothalamus",
  "Swimming",
  "Debilitating",
  "Incontinence",
  "Accountant",
  "Multivitamin",
  "Heart racing",
  "Tingling",
  "Muscle",
  "Cloudy urine",
  "Physiotherapy",
  "Knees",
  "Laceration",
  "Full blood count",
  "Stiff",
  "Cystitis",
  "Team",
  "Right hand",
  "Bad lower back",
  "Acne",
  "Standing up",
  "Needles",
  "Spotting",
  "Bell's palsy",
  "Long flight",
  "Cousin",
  "Throbbing",
  "Dehydration",
  "Hyperglycaemia",
  "Protruding",
  "Feeling distended",
  "Peeling",
  "Back",
  "Immunotherapy",
  "Therapist",
  "Massage therapy",
  "Night sweats",
  "Shooting sensation",
  "Chest",
  "Immunity",
  "Chest infection",
  "Business trip",
  "Bone marrow biopsy",
  "Cough",
  "Migraine",
  "Coeliac disease",
  "Left ventricle",
  "Stage 3",
  "Lupus",
  "Hydrocortisone",
  "Call centre",
  "Chest tightness",
  "Scuba diving",
  "Collarbone",
  "Rotator cuff",
  "Builder",
  "Glucosamine",
  "Dry skin",
  "Cracked skin",
  "Depression",
  "Milk",
  "Nightmares",
  "Carpenter",
  "Throat infection",
  "Meniere's disease",
  "Floaters",
  "Topical corticosteroids",
  "Vitamin D cream",
  "Clumsy",
  "Irritated",
  "Rigid",
  "Elbow",
  "Driving",
  "Jerking",
  "Yoga class",
  "Balanced",
  "Phototherapy",
  "Hiking",
  "Blurred vision",
  "Concentrate",
  "Proton pump inhibitor",
  "Computer programmer",
  "Ginseng",
  "Crackers",
  "Craving",
  "Small intestine",
  "Patches",
  "Journalist",
  "Fainting",
  "Fatigue",
  "Bloated",
  "Exhaustion",
  "Colonoscopy",
  "Breast cancer",
  "Stomach ulcer",
  "Mint tea",
  "Barium enema",
  "Alzheimer's",
  "Emphysema",
  "Cuts",
  "Designer",
  "Blood ELISA",
  "Graphic designer",
  "Garlic",
  "Nasal spray",
  "Overactive thalamus",
  "Needle",
  "Oats",
  "Buzzing",
  "Stinging",
  "Sour",
  "Temper",
  "Rubella",
  "Bright sunlight",
  "Pounding sounds",
  "Irritable",
  "Dark red",
  "Red",
  "Protein",
  "Coffee",
  "Caffeine",
  "ANA test",
  "Mild grade fever",
  "Both shoulder blades",
  "Hearing loss",
  "Non-alcoholic fatty liver",
  "Energy",
  "Addison's disease",
  "Cortisol day curve",
  "Asthma",
  "Exercises",
  "Unbearable",
  "Orange fruit",
  "Larynx",
  "Cancer",
  "Blind",
  "Fights",
  "IT consultant",
  "Bite",
  "Jerky",
  "Thick",
  "Stiffness",
  "Freelance writer",
  "Thalassaemia",
  "Burning sensation",
  "Soothing ointment",
  "Drive",
  "Toes",
  "Tonsillitis",
  "Itchy",
  "ADHD",
  "Apprentice",
  "Headache",
  "Floating",
  "Numb",
  "Sciatica",
  "Eczema",
  "Nose bleeding",
  "Tramadol injection",
  "High arch",
  "Ice pack",
  "Bleeding",
  "Civil",
  "Cramping",
  "Tramadol",
  "Type 2 diabetes",
  "Shellfish",
  "Cycling",
  "Bladder",
  "Security guard",
  "Droopy",
  "Grips",
  "Pregnancy test",
  "Pre-diabetes",
  "Urinary infection",
  "Ovarian cyst",
  "Metformin",
  "Vomit",
  "Colon irritable syndrome",
  "Bloating",
  "Persistent diarrhoea",
  "Tour guide",
  "Big toe",
  "Elastic band",
  "Aching",
  "Ankle",
  "Tinnitus",
  "Ginger",
  "Meniscus",
  "Driver",
  "Orange juice",
  "Joint",
  "food cut",
  "Both eyes",
  "Anti-inflammatory",
  "Gripping",
  "Tendon",
  "Farmer",
  "Brace",
  "Cod liver oil",
  "Ointment",
  "Stone",
  "Darker",
  "Head whiplash",
  "Racing",
  "Financial adviser",
  "Astigmatism",
  "Blinking",
  "Topical antibiotic",
  "White",
  "Dandruff",
  "Tea tree oil",
  "Metallic",
  "Dark and red urine",
  "Home remedies",
  "Steroid cream",
  "Cold compression",
  "Salt",
  "Constipation",
  "Lung cancer",
  "Fluttering",
  "A surveyor",
  "A freelance writer",
  "Arches",
  "Aerobic exercise",
  "Oily fish",
  "Bicycle",
  "Humidity",
  "Padding",
  "Zinc",
  "Right thumb",
  "Cold water",
  "Ketogenic",
  "Breathless",
  "Dull ache",
  "Eyebrow",
  "Glaucoma",
  "Patch",
  "Project manager",
  "Oral contraceptive",
  "Eye drops",
  "Concentration",
  "Antacid",
  "Tummy",
  "Calves",
  "Oil",
  "drooping",
  "Cheeks",
  "Peanuts",
  "Chewing",
  "Ladder",
  "Film",
  "Surgery",
  "Torn ligament",
  "Nosebleeds",
  "Heat pack",
  "Counselling",
  "Strangulation",
  "Lying flat",
  "Dyspepsia",
  "Engineering",
  "Wheezy",
  "Electrotherapy",
  "Bruise",
  "Loss of appetite",
  "Petechial rash",
  "Clingy",
  "TIA",
  "Antacids",
  "Repetitive nerve stimulation",
  "Heavy lifting",
  "Flu vaccination",
  "Drooping eyelid",
  "Osteoporosis",
  "Ligaments",
  "Spiders",
  "Palms",
  "Greasy",
  "Pulmonary embolism",
  "Whooping cough",
  "Bad constipation",
  "Dietary issue",
  "Construction worker",
  "Permanent",
  "Tooth extraction",
  "Cardiologist",
  "Cauterisation",
  "Beta blockers",
  "Pulsing",
  "Ablation",
  "Scrotum",
  "Apnoea",
  "Pleurisy",
  "Right shoulder",
  "Hockey",
  "Temporary blindness",
  "Juvenile rheumatoid arthritis",
  "Appendicitis",
  "Anorexia nervosa",
  "Bitter",
  "Dehydrated",
  "Chiropractic",
  "Urethral dilation",
  "Headaches",
  "Deodorant",
  "Perfume",
  "Chins",
  "General anaesthesia",
  "Arthritis",
  "Coconut oil",
  "Internal nasal packing",
  "Dairy issue",
  "C-reactive protein",
  "Teeth",
  "Constipated",
  "Diarrhoea",
  "Blisters",
  "Restless",
  "Gastric reflux",
  "Kidney stones",
  "Yoghurt",
  "Fluid",
  "Oat",
  "Stye",
  "Crusting",
  "Muscle tone",
  "Fidgety",
  "Arms",
  "Rheumatic fever",
  "Endometriosis",
  "Brain fog",
  "Eyelids",
  "Dental hygienist",
  "Tremor",
  "Wave hands",
  "Botox",
  "Vitamin B6",
  "Twin sister",
  "Bipolar",
  "Transfusion",
  "Pelvic adhesions",
  "Typing speed",
  "Iron deficiency anaemia",
  "Trembling",
  "Cracked",
  "Ibuprofen",
  "Contagious",
  "Purple rash",
  "Gymnastics",
  "Keyboard",
  "Massage",
  "Strapping",
  "Grabbing",
  "Drenching",
  "Web designer",
  "Complex partial",
  "Tonic-clonic",
  "Bump on head",
  "VNS therapy",
  "Convulsions",
  "Resistance band",
  "Stretch",
  "Cortisone injection",
  "Kidney infection",
  "Weaknesses",
  "Jabbing",
  "Insomnia",
  "Muscles",
  "Driving licence",
  "Driving instructor",
  "Meningitis",
  "Intravenous therapy",
  "Suprapubic catheter",
  "Sphincter",
  "Bladder spasm",
  "Different food",
  "Swelling",
  "Saline drip",
  "Colouring",
  "Bread",
  "Agoraphobia",
  "Thumb",
  "Handwriting",
  "Chocolate period",
  "Self-harm",
  "Shivering",
  "Flat",
  "PPI",
  "Heparin",
  "Heart murmur",
  "Breastfeed",
  "Civil engineer",
  "Sprain",
  "Superior area",
  "Muscular dystrophy",
  "Chubby",
  "Swollen tongue",
  "Rashes",
  "Stretching",
  "Lifting",
  "Judge distance",
  "Falls",
  "Dizziness",
  "Grandmother",
  "Anxious",
  "Garlic pills",
  "Wrists",
  "Smelling",
  "Administrator",
  "Stomach cramps",
  "Soreness",
  "Dust",
  "Occupation",
  "Ticket collector",
  "Freelance journalist",
  "Type 1 diabetes",
  "Acoustic neuroma",
  "Neck pain",
  "Stutter",
  "Lumps",
  "Crutches",
  "Tendonitis",
  "Sedentary life",
  "Superior aspect",
  "Groggy",
  "Factory cleaner",
  "Bulimia",
  "Left buttock",
  "Dread",
  "Swallowing",
  "Interpersonal Therapy",
  "Pink eye",
  "Periods",
  "Confidence",
  "Chocolate",
  "Cheese",
  "Hand",
  "Immune disorder",
  "Sleepless",
  "Pituitary MRI",
  "Penicillin",
  "Forceps",
  "CVS",
  "Siblings",
  "Breech",
  "Infertile",
  "Probiotic",
  "Sailor",
  "Perfumes",
  "Gentle exercise",
  "Unsociable",
  "Office",
  "Flight attendant",
  "Relief",
  "Speech impairment",
  "Gallstones",
  "Sticky",
  "Pneumonia",
  "White crust",
  "Affection",
  "Panic",
  "Hip",
  "Down syndrome",
  "Massage therapist",
  "Vegetarian",
  "Biopsy",
  "Malaria",
  "Contiguous",
  "Sick and dizzy",
  "Congested vein",
  "Beeswax",
  "Styes",
  "Complications",
  "Lying down",
  "Melanoma",
  "Teething",
  "Rugby",
  "Ultrasound",
  "Cry",
  "Chemotherapy",
  "Frozen egg",
  "Hair loss",
  "Hot pads",
  "Panic attacks",
  "Bruises",
  "Fertility",
  "Oral contraceptives",
  "Heat packs",
  "Malaria tablets",
  "Adhesion",
  "Botox injection",
  "Anaesthetic medication",
  "Spasm",
  "Intermittent catheter",
  "Pins and needles",
  "Bitter taste",
  "Software developer",
  "Watery",
  "Tumour markers",
  "Abdominal area",
  "Presentation",
  "Wedding",
  "Lymph nodes",
  "Irritable bowel syndrome",
  "Menopause",
  "Sprain ankle",
  "Hand cream",
  "Environmental engineering",
  "Tennis ball",
  "Flat position",
  "Wheezing",
  "Psoriasis",
  "Urinary tract infection",
  "Paralysis",
  "Personal trainer",
  "Crowded places",
  "Finances",
  "Radiation",
  "Basketball",
  "Market research",
  "Badly taste",
  "Bad odour",
  "Blood tests",
  "Scratching",
  "Sharp",
  "Punctured lung",
  "Appendectomy",
  "Sinus inflammation",
  "Scarlet fever",
  "University lecturer",
  "Fertility treatment",
  "Thirsty",
  "Drowsy",
  "Migraines",
  "Popping sound",
  "Oesophageal cancer",
  "Gluten-free",
  "Obese",
  "Shower gels",
  "Thighs",
  "Fine",
  "Chickenpox",
  "Immune system",
  "Programmer",
  "Calamine lotion",
  "Eyebrows",
  "Herbal oil",
  "Iron deficiency",
  "Weight gain",
  "Impaction",
  "Engineer",
  "Building sites",
  "Blotches",
  "Heel",
  "Sway",
  "Disorientation",
  "Emotional outbursts",
  "Choking",
  "Autism",
  "Holter monitor",
  "Muscle biopsy",
  "Blood thinners",
  "Unsaturated fats",
  "Dizzy spells",
  "Bereavement",
  "Dancing instructor",
  "Died",
  "Ear infection",
  "Alzheimer's disease",
  "Femur",
  "Rods",
  "Jump",
  "Shoulders",
  "Goalkeeper",
  "Tea",
  "Tomatoes",
  "Central nervous system",
  "Left calf",
  "Varicose veins",
  "Wrist brace",
  "Metal rod",
  "Bent",
  "Strawberry tongue",
  "Washing hair",
  "Knife and fork",
  "Bloodshot",
  "Fingertips",
  "Cracked lips",
  "Japan",
  "Epilepsy",
  "Booster injection",
  "Febrile convulsion",
  "Febrile convulsions",
  "Pressure sores",
  "Events manager",
  "Change dressing",
  "Preventer",
  "Steroid",
  "Menstruation",
  "Car accident",
  "Fuzzy",
  "Injection",
  "Lunch time",
  "Swallow",
  "Vocabulary",
  "Vascular",
  "Eating",
  "Some sort of food",
  "Urinalysis",
  "Deafness",
  "Magazine editor",
  "Visual perception",
  "Heartbeats",
  "Tightness",
  "Financial problems",
  "Cut two fingers",
  "Lung expansion",
  "Tantrum",
  "Groin area",
  "Asking",
  "Indigestion",
  "Cloudy",
  "Popping",
  "Swollen",
  "Physiotherapy session",
  "Calf",
  "Mouth ulcers",
  "Painkillers",
  "Rib cage",
  "Drained",
  "Tonsillectomy",
  "Potassium level",
  "Anaemia",
  "Indoor exercises",
  "Tongue-tie",
  "Crusty mucus",
  "White crusts",
  "Antihistamine",
  "Clockwise",
  "Social gatherings",
  "Vomited",
  "Stomach",
  "Groin",
  "In concentration",
  "Baggage",
  "Tailor",
  "Savoury snacks",
  "Dragging",
  "Spider",
  "Whiplash injury",
  "Pituitary",
  "Red spots",
  "Dry mouth",
  "Distracted",
  "Ginseng supplements",
  "Senna tablets",
  "Neighbour",
  "Burping",
  "Sales manager",
  "Pre-eclampsia",
  "Four months",
  "Meat",
  "Oranges",
  "Lemonades",
  "Prostatic cancer",
  "Cirrhosis",
  "Smoking",
  "Intermittent",
  "Blurred",
  "Motivation",
  "Sinusitis",
  "Swollen ankle",
  "Mumps",
  "Magnesium tablets",
  "Widow",
  "Building inspector",
  "Amnesia",
  "Testosterone",
  "Botanist",
  "Left tibia",
  "Knife",
  "Low fat",
  "Low-fat diet",
  "Gallbladder",
  "Self-catheterisation",
  "Zika virus",
  "Clumps",
  "IV antibiotics",
  "Specialised message",
  "Compression socks",
  "Swelling up",
  "Fever",
  "Liposuction",
  "Croup",
  "Fell",
  "Steady",
  "Glue ear",
  "Agitated",
  "Ammonia",
  "Malarone tablets",
  "Broken ribs",
  "Heartbeat",
  "Anger",
  "Bump his head",
  "Memory",
  "Partial seizure",
  "Paracetamol",
  "Beta blocker",
  "Joints pain",
  "Many strokes",
  "Freeze",
  "Blood clots",
  "Financial advisor",
  "Frontal lobe",
  "Seizures",
  "Loss of hearing",
  "Social gathering",
  "Propranolol",
  "Tetanus",
  "Mouth ulcer",
  "16mg",
  "Squat position",
  "Acute inflammation",
  "Anti-clockwise",
  "Crackling",
  "Patella",
  "Exercise straps",
  "Hamstring",
  "Urgency",
  "Intense",
  "Cold sores",
  "Heat pads",
  "Lying flat position",
  "Proton pump inhibitors",
  "Sweating",
  "Breathlessness",
  "Pink eyes",
  "Gastric bypass surgery",
  "Above normal",
  "Firefighter",
  "Weightlifter",
  "Allergy test",
  "Dementia",
  "Training",
  "Soccer",
  "Alcohol",
  "Fibromyalgia",
  "Antispasmodic",
  "Disc prolapse",
  "Mechanic",
  "Bump on the head",
  "Bumps",
  "Trance",
  "Dribble",
  "Ribs",
  "Heparin injections",
  "Vertigo",
  "Concussions",
  "Corticosteroid injection",
  "Ethanol",
  "Carbohydrates",
  "Golf",
  "Thyroid",
  "Steroid injection",
  "3 miscarriages",
  "Uterine cancer",
  "Uterine balloon",
  "Light bleeding",
  "Kidney stone",
  "Vitamin B12",
  "Gastric flu",
  "Fitful",
  "Law",
  "Isolated",
  "Clouded",
  "Joints",
  "Cut my food",
  "Physical activity",
  "Graded exercise therapy",
  "Faint",
  "Sensitivity to light",
  "Underactive thyroid",
  "Antiseptic shampoo",
  "Irritated skin",
  "Dilantin",
  "Rhinocort nasal spray",
  "Mucofen",
  "Flurbiprofen",
  "Klonopin",
  "Rivaroxaban",
  "Mitomycin",
  "Flomax",
  "Advair diskus",
  "Celebrex",
  "Neurontin",
  "Cyclophosphamide",
  "Morphine",
  "Zolpidem",
  "Nitroglycerin",
  "Clopidogrel",
  "Keflex",
  "Atenolol",
  "Sodium bicarbonate",
  "Neoprene",
  "Cardizem",
  "Metoprolol",
  "Hydralazine",
  "Labetalol",
  "Levothyroxine",
  "Zyrtec",
  "Proscar",
  "Synthroid",
  "Motrin",
  "Avelox",
  "Codeine",
  "Chlordiazepoxide",
  "Simvastatin",
  "Flagyl",
  "Daptomycin",
  "Primaxin",
  "Methadone",
  "Levaquin",
  "Floppy",
  "Tongue",
  "Earache",
  "Spasms",
  "Gums",
  "Pus",
  "Hard",
  "Lighter",
  "New mouse",
  "Golf ball",
  "Restless legs syndrome",
  "Carpal tunnel syndrome",
  "Scar",
  "Aspiration",
  "Fracture",
  "Drill",
  "Mood swing",
  "Constant pain",
  "Cricking",
  "Jewellery maker",
  "Dialysis",
  "Itchy leg",
  "Verapamil",
  "Vegetarian diet",
  "Dietary",
  "Dry cough",
  "Respiratory infection",
  "Laparoscopy",
  "Blood test",
  "Memory lapse",
  "Fidget",
  "Strengthening exercises",
  "Stumbling",
  "Sides of buttocks",
  "Dairy",
  "Diary",
  "Beer",
  "Bear",
  "Liver",
  "Eyes",
  "Firefighters",
  "ACE inhibitors",
  "Brown marks",
  "Rheumatology",
  "Big toe arthritis",
  "Baclofen",
  "High-impact sports",
  "Sugar",
  "Frightening",
  "Vibrating",
  "Restricted diet",
  "Dermatology consultation",
  "Allergy",
  "Pruritus",
  "Hives",
  "Orange",
  "Lemonade",
  "Multiple organ failure",
  "Peritonitis",
  "Stomach pain",
  "Hernia",
  "Ventilation",
  "Stoma",
  "Growing pain",
  "Flat mattress",
  "Coma",
  "Ventilator",
  "Abdominal pain",
  "Tonsil",
  "Withdrawn",
  "Limping",
  "limb",
  "Ankles",
  "Healthy",
  "Sister",
  "Aerobics",
  "Blood transfusion",
  "Perfumed",
  "Hydrated",
  "Emotional",
  "Skin is dry and flaky",
  "Diet free of gluten",
  "Cataract",
  "Left thumb",
  "Flaky",
  "Drinking tea",
  "Water",
  "Peanut",
  "Active thyroid",
  "Nephrologist",
  "Neurologist",
  "High-fibre diet",
  "Kidney cancer",
  "Kidney graft",
  "Canal",
  "Two toes",
  "Abdomen",
  "Warehouse",
  "Blotchy",
  "Leathery skin",
  "Longstanding",
  "Bandage",
  "Panic attack",
  "Hypertension",
  "Herbalist",
  "Guitar",
  "Smell",
  "Weightlifting",
  "Obesity",
  "Convenience diet",
  "Vascular dementia",
  "Leukaemia",
  "Fractured rib",
  "Ears",
  "Sinuses",
  "Management",
  "Scoliosis",
  "Breastfeeding",
  "Absence seizures",
  "Rheumatoid fever",
  "Echo",
  "Stuttered",
  "Hacking",
  "Whispering",
  "Dog trainer",
  "Lupus groin",
  "Hammer",
  "Blurring of vision",
  "Fast food",
  "Voice",
  "Glue",
  "Oral antibiotics",
  "Mushrooms",
  "Sour taste",
  "Sore throat",
  "warm compresses",
  "Dental assistant",
  "Salmonella",
  "Melatonin",
  "Regurgitation",
  "Computer",
  "Lunch",
  "Injections",
  "Bracing",
  "June",
  "Muscle relaxant",
  "Prickling",
  "Knee replacement",
  "Humid",
  "Dark",
  "Hepatitis",
  "Tai chi",
  "Refreshed",
  "Bilirubin",
  "Dreadful fatigue",
  "Stabbing",
  "Restless at school",
  "Handshake",
  "Dark urine",
  "Slurred",
  "Continence",
  "Neighbours",
  "Savoury",
  "Baggage handler",
  "Luggage",
  "Vitiligo",
  "Commercial artist",
  "Strength",
  "Laxatives",
  "Junk food",
  "Climbing stairs",
  "Jaw exercise",
  "Uric acid",
  "Software designer",
  "Lifting weights",
  "Calcium",
  "Preventive measures",
  "Ulcerative colitis",
  "Pressure",
  "Discolouration",
  "Sodium",
  "Magnesium",
  "Potassium",
  "Environmental engineer",
  "Sprained ankle",
  "Dressing",
  "Temperature",
  "Tetanus vaccination",
  "Difficult",
  "Different",
  "Deficiency",
  "Awareness",
  "Sharp mind",
  "Osteomyelitis",
  "Nail",
  "Opioids",
  "Pelvic ultrasound",
  "Clots",
  "Childcare assistant",
  "Retirement",
  "Dancing",
  "Cranberry supplement",
  "Blurring",
  "Hopelessness",
  "Ovarian cysts",
  "Tingling sensation",
  "Rubbing ointment",
  "Tiger balm",
  "Unsteady",
  "Jet lag",
  "Toe",
  "Tarsal fracture",
  "Chest pain",
  "Throat cancer",
  "Triptan",
  "Imbalance",
  "Heavy",
  "Ferritin",
  "Amino acid",
  "Bold patches",
  "Anxiety attacks",
  "Hotel receptionist",
  "Poliovirus",
  "Thyroid function test",
  "Hormonal imbalance",
  "Scabbing",
  "Scabies",
  "Right knee",
  "Bunion",
  "Distorted",
  "Stationary life",
  "DM",
  "Trapped nerve",
  "Lump",
  "Big toes",
  "Kidney disease",
  "Chiropractor",
  "Bending over",
  "Dairy products",
  "Intense burning",
  "A translator",
  "Playing squash",
  "Whiplash",
  "Mouse",
  "An accountant",
  "An underactive thyroid",
  "Pelvic congestion",
  "Mild fever",
  "Bone loss in jaw",
  "A web designer",
  "Canker sores",
  "Epilepticus",
  "Whipple's disease",
  "Gastroenterology",
  "Involuntary",
  "Pepper",
  "Peppermint",
  "Cricket",
  "Uncomplicated pregnancy",
  "Reflexes",
  "Imitating",
  "Breakfast",
  "Rely on",
  "Exacerbate",
  "Housewife",
  "Work",
  "Patchy",
  "Inflammatory",
  "Inflammation",
  "Inflamed",
  "Exercise",
  "Light",
  "Regular",
  "Uterine balloon therapy",
  "Preventative medicine",
  "Miscarriages",
  "High-impact sport",
  "A sprain",
  "Laser",
  "Traumatic",
  "Bad haemorrhage",
  "Bend it",
  "Brownish",
  "An ultrasound",
  "Appetite",
  "Shockwave surgery",
  "Reflux",
  "Boxing",
  "Homemaker",
  "Food poisoning",
  "Workaholic",
  "Electric",
  "Shock",
  "Seafood",
  "Shower gel",
  "Sitting down",
  "Cervical cancer",
  "Spirometry",
  "Excessive exercise",
  "Oil paints",
  "Layout",
  "Clothes",
  "Movement",
  "Climbing upstairs",
  "Heaviness",
  "Speaking",
  "Slow",
  "Wisdom teeth",
  "Beauty therapist",
  "Stairs",
  "Bronchitis",
  "Graft",
  "High-need baby",
  "Cleft lip",
  "Grommet",
  "Mushroom",
  "Uncooperative",
  "Picky",
  "Behaviour",
  "Muscle tones",
  "Waking scheduled",
  "Judo",
  "Waved hand",
  "Armpit",
  "Sweat",
  "Biologist",
  "Blister",
  "Taste",
  "Elbow joint",
  "Both calves",
  "Backhand",
  "Systemic lupus",
  "Blindness",
  "Warm compression",
  "Serious wrist fracture",
  "Topical antibiotics",
  "Whisper",
  "Repeat",
  "Constricted",
  "Steroid tablet",
  "Plenty fluids",
  "Wrist joint",
  "Slurred speech",
  "Flu vaccine",
  "Thymus gland",
  "Badminton sport",
  "Spitting",
  "Shoulder dystocia",
  "Nursery",
  "Tummy ache",
  "Chest X-ray",
  "Tetanus vaccine",
  "Sharp brain",
  "Convenient foods",
  "Pain",
  "Stiffened",
  "Left ankle",
  "Growing pains",
  "Cortisone cream",
  "Left ventricular hypertrophy",
  "Absence seizure",
  "Convenience food",
  "Coughing fits",
  "2 toes",
  "Piercing headache",
  "Leathery",
  "Hip joint",
  "Bold patch",
  "Coordination",
  "Thyroid function",
  "Anxiety attack",
  "Urinating",
  "Blue limbs",
  "Vibration",
  "Short of breath",
  "Fitness",
  "Fibre diet",
  "Antidepressant",
  "Embolisation",
  "Peanut allergy",
  "Both knees",
  "Puberty",
  "Traffic noise",
  "Web organiser",
  "Pacemaker",
  "Skin rash",
  "Housebound",
  "Sticky eyes",
  "Uncomfortable stomach",
  "Hip replacement",
  "Alternative therapy",
  "Dry",
  "Awful",
  "Gluten-free diet",
  "Hydration",
  "Upper limb",
  "Anaerobic",
  "Exam",
  "Multiple system failure",
  "Stomach ache",
  "Colostomy",
  "Loosening",
  "Losing weight",
  "Vegetables",
  "Cholecystectomy",
  "Typically",
  "Lifting things",
  "Lobe",
  "A type of viruses",
  "Back ankle",
  "Bend",
  "Bend over",
  "Bout",
  "Bump",
  "Chapped lips",
  "Cold compressor",
  "Crackling sounds",
  "Dermatitis",
  "Deteriorate",
  "EEG",
  "Electroencephalogram",
  "Excruciated",
  "Falling",
  "Financial",
  "Fingers",
  "Invasive",
  "Invitations",
  "Jobbing",
  "Gapping",
  "Kidney",
  "Loss of energy",
  "Meals",
  "Launch",
  "Normal",
  "Off-colour",
  "Oil paint",
  "Opioid",
  "Optic disc",
  "Perception",
  "Pounding sound",
  "Prevention",
  "Psychological assessment",
  "Radiotherapy",
  "SLE",
  "Systemic lupus erythematosus",
  "Salad",
  "Self-conscious",
  "Shadow",
  "Shooting",
  "Spots",
  "Tension headaches",
  "Thyroid disease",
  "Toys",
  "Twisting",
  "Attack",
  "Autoimmune",
  "Bouncing sounds",
  "Brain scan",
  "Cleaner",
  "Confused",
  "Ear glue",
  "Night sweat",
  "Oxygen",
  "Sense of balance",
  "Sensitive to light",
  "Shooting pain",
  "Pelvic inflammatory disease",
  "Fallopian tubes",
  "Appendix",
  "Appendicectomy",
  "Miscarriage",
  "Shopping",
  "Thyroxine",
  "Tummy pain",
  "Belly pain",
  "X-ray",
  "Warm compress",
  "Antibiotic",
  "Sit",
  "bicarbonate",
  "Hydrochlorothiazide",
  "Fractures",
  "Kidney transplant",
  "Aggressive",
  "CBT",
  "Smoke inhalation",
  "Liver cancer",
  "Vibrating tool",
  "Dry crackers",
  "Glands",
  "Throat",
  "Anterior nasal packing",
  "Muscle fasciculation",
  "Exacerbated",
  "Medial cruciate ligament",
  "Anterior drawer test",
  "Abrasion",
  "Genetic",
  "Abdominal rigidity",
  "Stomach suction",
  "Tachycardia",
  "Energy levels",
  "Cardiomyopathy",
  "Angiogram",
  "Condoms",
  "Calcium deficiency",
  "Urge",
  "Tomato",
  "Cognitive Behavioural Therapy",
  "Dull aching",
  "Trial and error",
  "Cortisone",
  "ACE inhibitor",
  "Itchiness",
  "Belching",
  "Sturdy shoes",
  "Blocked up",
  "Congestion",
  "Suppository",
  "Whistling",
  "Angioplasty",
  "Aspirin",
  "Squinting",
  "OCD",
  "ECG",
  "Turnover",
  "Fluoxetine",
  "A little bit stressed",
  "Flossing teeth",
  "An extensive food allergy test",
  "Treatment",
  "Oral medications",
  "Short-sighted",
  "Short-sightedness",
  "Prenatal bruising",
  "Osteopathic chair",
  "Prilosec",
  "Persistent",
  "Unpredictable",
  "Prolapsing",
  "Throbbing pain",
  "Untreatable",
  "Maternal screening",
  "Administration via a pump",
  "Ineffective",
  "Puffing",
  "Fetoprotein",
  "Bloating sensation",
  "Free beta-hCG",
  "Electrical impulse",
  "Combination of treatment",
  "Frequent",
  "Inhibin A",
  "Antiviral cream",
  "Flare-up of scratchy",
  "Asthmatic inhalers",
  "Stiff feeling in neck",
  "Weepy",
  "Eye",
  "Amniocentesis",
  "Amoxicillin",
  "Swallowing difficulty",
  "Disappointed",
  "Amniotic level",
  "LASIK surgery",
  "Loss of memory",
  "Overwhelmed",
  "Coagulation profile",
  "Herbal medicines",
  "Sore in throat",
  "Iron studies",
  "Implanted contact",
  "Marijuana",
  "Shortness of breath",
  "Iron stores",
  "Cotton bags",
  "Recreational drugs",
  "Illicit drugs",
  "Impaired Amsler chart",
  "Inguinal hernia repair",
  "Sceptical",
  "Bone grafting",
  "Cover",
  "Boldly forward",
  "Airway device",
  "Malarone",
  "Frustrating",
  "Cholesterol level",
  "Mefloquine",
  "Doxycycline",
  "CT scan",
  "PET scan",
  "Chloroquine",
  "Anti-malaria",
  "OTC",
  "Over-the-counter",
  "Date and time",
  "Diet",
  "Disease",
  "Family members",
  "Referral",
  "Noun",
  "Months",
  "Fibres",
  "Father",
  "Nutritionist",
  "Leaflet",
  "Weeks",
  "Obsessive compulsive disorder",
  "Mother",
  "Pharmacy",
  "Days",
  "Meat lovers",
  "MI",
  "Myocardial infarction",
  "Aunt",
  "Social worker",
  "Couple of months",
  "Spinach",
  "Transposition of great vessels",
  "Unclean",
  "Optometrist",
  "2 times",
  "Common cold",
  "Brother",
  "Ophthalmologist",
  "Heavy suitcase",
  "Carnivore",
  "Obstetrician",
  "Gynaecologist",
  "Paediatrician",
  "Contact lens",
  "Leafy green",
  "Daughter",
  "Rigid contacts",
  "Removal solution",
  "Hobbies",
  "Egg",
  "Senior special cleaner",
  "Soccer ball",
  "IBD",
  "Inflammatory bowel disease",
  "Nephew",
  "Cornea",
  "Rugby ball",
  "Chaotic",
  "Ballet dancing",
  "Soya",
  "Grandma",
  "Audiologist",
  "Lubricant",
  "Salmon",
  "Slipped disc",
  "Grandpa",
  "Paediatric dentist",
  "Microkeratome",
  "Running",
  "Tuna",
  "High fever",
  "Reading glasses",
  "Riding",
  "GP",
  "General practitioner",
  "Waviness in reading",
  "Macular degeneration",
  "Dermatologist",
  "Phone book",
  "Dumbbells",
  "Care assistant",
  "Pigments in retina",
  "Events organiser",
  "Professional",
  "Auditory",
  "Brainstem",
  "Executive director",
  "Physician",
  "Optic nerve",
  "Hair cell death",
  "Batteries",
  "High school teacher",
  "Neuropath",
  "Silicon tubes",
  "Haemochromatosis",
  "Rubber tubes",
  "Retailer",
  "Gingivitis",
  "Full-time job",
  "Leaking valve",
  "Periodontal disease",
  "Gum lump",
  "Lumpectomy",
  "Burnout",
  "PSA",
  "Prostate specific antigen",
  "Dental caries or decay",
  "Mental orphanage",
  "Meniscectomy",
  "Sunbeds",
  "Nephrectomy",
  "Obstructive shock",
  "Pallor",
  "HIV test",
  "Sunscreen",
  "Giardia",
  "Dyspnoea",
  "MRI",
  "Magnetic resonance imaging",
  "Electrocardiogram",
  "Treadmill",
  "Splenectomy",
  "Spleen",
  "Amoebic dysentery",
  "Mental well-being",
  "Prolactin",
  "HTLV-1 virus",
  "LH kit",
  "Nauseous",
  "Cognitive impairment",
  "Sperm",
  "Quality",
  "Quantity",
  "Cystoprostatectomy",
  "Typhoid fever",
  "Masticatory muscle",
  "BMD test",
  "Mechanical ventilatory support",
  "Coronary stent",
  "Strain",
  "Tylenol",
  "Mammogram",
  "Carotid Doppler",
  "Carvedilol",
  "BRCA",
  "Chemical cauterisation",
  "Furosemide",
  "Conjunctival",
  "Icterus",
  "Dysmetria",
  "Amlodipine",
  "Carotid bruits",
  "Mastectomy",
  "Lightheaded",
  "Lightheadedness",
  "Ranitidine",
  "Renal scintigraphy",
  "Loud snoring",
  "Transvaginal probe",
  "Pigeon toe",
  "Wax and wane",
  "Cerebral palsy",
  "Electric shock",
  "Volvulus",
  "Diabetic retinopathy",
  "Myopia",
  "Hypermetropia",
  "Hereditary spherocytosis",
  "Neonate",
  "Narcissistic personality disorder",
  "D-dimer",
  "Schizophrenia",
  "Romberg test",
  "Lumbar lordosis",
  "Ejection fraction",
  "Xerostomia",
  "Allergic contact dermatitis",
  "Hydroquinone",
  "Seborrhoeic dermatitis",
  "Tamoxifen",
  "Lichen simplex",
  "Claritin",
  "Angioedema",
  "Augmentin",
  "Small meals",
  "Necrotising fasciitis",
  "Special food like yoghurt",
  "Alopecia",
  "Pool of porridge",
  "Raynaud's phenomenon",
  "Banana",
  "Postherpetic neuralgia",
  "Apple",
  "Lyme disease",
  "Sushi",
  "Ischaemic colitis",
  "Dried fruits",
  "Hypochondria",
  "Resin",
  "Haemophilia",
  "Apricot",
  "Skin prick testing",
  "Lamb meat",
  "Veal meat",
  "Glipizide",
  "Clotting factor",
  "Rice",
  "Pasta",
  "Lactose",
  "Winds",
  "Detrol",
  "Fluticasone spray",
  "Raffinose onion",
  "Pantoprazole",
  "Cabbage",
  "Warfarin",
  "Fructose",
  "Glucose",
  "Premarin",
  "Wheat",
  "Oestradiol",
  "Oestrogen",
  "Starch",
  "Dexamethasone",
  "Pear",
  "Pineapple",
  "Kiwi",
  "Citrus fruit",
  "OxyContin",
  "Cephalosporin",
  "Freak",
  "Buttoning",
  "Carry on",
  "Fomites",
  "Utensil",
  "Eye symptoms",
  "Foggy window",
  "Retinal detached",
  "Glasses",
  "Coloured contact lenses",
  "Vitrectomy",
  "Laser therapy",
  "Glare",
  "Twitch",
  "Nystagmus",
  "Ulcer",
  "Photophobia",
  "Corneal abrasion",
  "Vitreous",
  "Breastbone",
  "Pectus excavatum",
  "Funnel chest",
  "Clavicle",
  "Shoulder blade",
  "Scapula",
  "Dropping",
  "Feel dizzy",
  "High voice or sound",
  "Viral infection",
  "Labourer",
  "Flaky skin",
  "Greasy stool",
  "Colace",
  "BOSU ball",
  "Rehabilitation",
  "Lax or tender abdomen",
  "Barking cough",
  "Nasty cough",
  "Sperm banking",
  "Be in a state",
  "Get into a state",
  "Sponge bath",
  "Blowing",
  "Roaring",
  "Hissing",
  "Humming",
  "Breakthrough pain",
  "Clogged",
  "Bacon",
  "Crippled",
  "Lean meat",
  "Processed meat",
  "Feeling woozy",
  "Investigations",
  "Growth spurt",
  "Habit-forming",
  "Addictive",
  "Fluorescein",
  "Hacking cough",
  "Impending sensation of death",
  "Scheduled",
  "Intensified",
  "Sham",
  "Intermenstrual",
  "Post-coital bleeding",
  "Coital",
  "Coitus",
  "Jarring injury",
  "Movements",
  "Body parts",
  "Jerking movements",
  "Abdominal girth",
  "Knee clicking",
  "Belly",
  "Bum cheek",
  "Loosened stool",
  "Loosened bowel movements",
  "Ear",
  "Moaning",
  "Iliopsoas",
  "Muffled",
  "Lamina propria",
  "Niggling",
  "Nagging",
  "Loin",
  "Oozing of blood",
  "Overwhelming",
  "Slime",
  "Panicky",
  "Sole of foot",
  "Palm of hand",
  "Pass sand",
  "Pass gravel",
  "Stool",
  "Urine",
  "Supine",
  "Prone",
  "Pinch",
  "Pinched",
  "Pinchable",
  "Pitting oedema",
  "Waist",
  "Womb",
  "Uterus",
  "Scald",
  "Scalded",
  "Adhesive",
  "Searing pain",
  "Ambulate",
  "Ambulance",
  "Seborrhoeic",
  "Blend",
  "Skin tag",
  "Boil",
  "Burrow",
  "Grain",
  "Hair grain",
  "Slipped",
  "Slip",
  "Twisted disc",
  "Bone",
  "Slurring speech",
  "Chaos",
  "Sneezing",
  "Chores",
  "Soaked",
  "Soaking for periods",
  "Climb",
  "Soothe",
  "Damp weather",
  "Dozen",
  "Stabbing pain",
  "Erratic",
  "Sting",
  "Stung",
  "Flip top",
  "Burning pain",
  "Guitar string",
  "Feel full",
  "Stomping gait",
  "Scissoring gait",
  "Festinating gait",
  "Freezing gait",
  "Waddling or Trendelenburg gait",
  "Antalgic gait",
  "Stooped gait",
  "Stooping walk",
  "Stooped posture",
  "Hold",
  "Striking",
  "Kindergarten",
  "Struvite stone",
  "Maternity",
  "Stuttering",
  "Momentum",
  "Sudden burst",
  "Mortgage",
  "Symptoms subsided",
  "Nimbly",
  "Tartar",
  "Overlook",
  "Tear",
  "Torn",
  "Trim",
  "Chop",
  "Dice",
  "Perspiration",
  "Tearing",
  "Ripping sensation",
  "Terrible",
  "Trouble",
  "Terrible pain",
  "Quiz",
  "Throw up",
  "Recuperation",
  "Toothache",
  "Spiritual",
  "Unattainable",
  "Susceptible",
  "Intolerable",
  "Sustainable",
  "Venomous",
  "Tease out",
  "Vexing pain",
  "Teeter",
  "Worn out",
  "Very tired",
  "Twinge",
  "Worrisome",
  "Vulnerable",
  "Moan",
  "Sleepy",
  "Back pain",
  "Cold",
  "Pain relief",
  "Health check-up",
  "Hospitalisation",
  "Murmur",
  "Barium meal",
  "Decaffeinated",
  "Graded exercise",
  "pre-diabetic",
  "squash",
  "Uncomplicated",
  "Wisp",
  "Losartan",
  "Atacand",
  "Plavix",
  "Omeprazole",
  "Albuterol",
  "Nasacort",
  "Ritalin",
  "EpiPen",
  "Mint leaves",
  "Remedies",
  "Decongestant",
  "Moisturiser",
  "Petroleum jelly",
  "Barrister",
  "Bartender",
  "Geneticist",
  "Insurer",
  "Kinesiologist",
  "Osteopath",
  "Otolaryngologist",
  "Podiatrist",
  "Rheumatologist",
  "Roof tiler",
  "Sibling",
  "Seller",
  "Darts Playing",
  "Sole Guardian",
  "Lorry Driver",
  "Spouse",
  "Amblyopia",
  "Azotaemia",
  "Bariatric",
  "Bouts",
  "Bulimia nervosa",
  "Dumping syndrome",
  "Dust mites",
  "Scaly rash",
  "Head lice",
  "Helicobacter pylori",
  "Infarcts",
  "Nocturnal",
  "Nocturia",
  "Odontalgia",
  "Oedema",
  "Phlegm",
  "Plaque",
  "Precocious puberty",
  "Scurvy",
  "Torsion",
  "Wart",
  "Athlete",
  "Athletic",
  "Baseball",
  "Camping",
  "Lawn Mowing",
  "Netball",
  "Nordic Walking",
  "Rowing",
  "Climbing",
  "Helmet",
  "Skiing",
  "Tournament",
  "Fuzziness",
  "Aches",
  "Agony",
  "Misaligned",
  "Breast dimpling",
  "Bullet",
  "Burbling",
  "Burp",
  "Colicky pain",
  "Breaking wind",
  "Flatulence",
  "Flickering",
  "Bent knee",
  "Cracking sound",
  "Crackling sound",
  "Crackling my knuckles",
  "Knotted sensation",
  "Lockjaw",
  "Hand splints",
  "Handrails",
  "Immobilisation boot",
  "Imodium",
  "Lice comb",
  "Ecstasy",
  "MDMA",
  "Opiate mix",
  "Pads and Tampons",
  "Peppermint oil",
  "Pethidine",
  "Prednisolone",
  "Prednisone",
  "Remedy",
  "Sore",
  "Towel",
  "Stick",
  "Zoloft",
  "Butter",
  "Crisps",
  "Chips",
  "Legumes",
  "Regime",
  "Milky puddings",
  "Refined food",
  "Soy",
  "Soybean",
  "Rye",
  "Barley",
  "Barely",
  "Cholangiogram",
  "Cardiotocography",
  "Colposcopy",
  "Cystourethroscopy",
  "Down gaze",
  "Horizontal gaze",
  "Scintigraphy",
  "Hamstrings",
  "Quads",
  "Achilles",
  "Belly button",
  "Navel",
  "Umbilicus",
  "Lean body",
  "Hump",
  "Waste",
  "Cannabis",
  "Freak out",
  "Utensils",
  "Scarring",
  "Anaesthesia",
  "Analgesia",
  "Urinary retention",
  "Intravenous",
  "Surgeon",
  "Surgical",
  "Ultrasonography",
  "Traffic accident",
  "Equipment",
  "Reconstruction",
  "Weight-bearing exercises",
  "Elevation",
  "Vocabularies",
  "Stimulation",
  "Enlarged prostate",
  "Fibre",
  "Products",
  "Herpes simplex",
  "Frequently",
  "Loose stool",
  "Sensitivity",
  "Debilitated",
  "Induced coma",
  "Compression stockings",
  "Gastrectomy",
  "Foam",
  "Noticeable",
  "Christmas",
  "Stooped",
  "Independent",
  "Eyesight",
  "Aqueous gel",
  "Temporary",
  "Teenage",
  "Evidence",
  "Malignant",
  "Stripping technique",
  "Platelets",
  "Spontaneous",
  "Haemoglobin",
  "End-stage renal failure",
  "Tiny filters",
  "Impairment",
  "Abstain",
  "Substance abuse",
  "Abnormalities",
  "Viral myocarditis",
  "Hypothyroidism",
  "Recruitment consultant",
  "Fingernails",
  "Toenail",
  "Suppress",
  "Gastric dumping syndrome",
  "Incredibly",
  "Bulging out",
  "Gradual",
  "Reassurance",
  "Muscle relaxants",
  "Parkinson's disease",
  "Recovery",
  "Shifty",
  "Ativan",
  "Eases",
  "Psychiatrist",
  "Separated",
  "Cigarettes",
  "Septoplasty",
  "Nostril",
  "Deviated septum",
  "Invasion",
  "Analgesic cream",
  "Occupational therapist",
  "Lukewarm",
  "CrossFit",
  "Sudden",
  "Dope smoker",
  "Hire car driver",
  "Humidifier",
  "Recurring lung infection",
  "Stingy",
  "Researcher",
  "Grocery",
  "Insect repellent",
  "Stamina",
  "Duodenal ulcer",
  "Wasp sting",
  "Condom",
  "Crowded",
  "Fatigued",
  "Anticonvulsant",
  "Severe",
  "Aromatherapy",
  "Air conditioning",
  "Abscess",
  "Millilitre",
  "Distended abdomen",
  "Temple",
  "Strawberries",
  "Fixation",
  "Irritants",
  "Pillow case",
  "District",
  "Prescribed",
  "Prescription",
  "Tumour",
  "Suicidal",
  "Conservative",
  "Fullness in ears",
  "Businessman",
  "Relieved",
  "Lonely",
  "Loneliness",
  "Arrhythmia",
  "Additional tests",
  "Ketones",
  "Gestational diabetes",
  "Contraception",
  "Dysfunctional",
  "Transvaginal ultrasound",
  "Meningococcal",
  "Liquid morphine",
  "Absorb",
  "Malabsorption",
  "Pouch",
  "Intersection",
  "Holidays",
  "Malaise",
  "Measles",
  "Gassy",
  "Strung",
  "Rupture",
  "Rapture",
  "Electrolytes",
  "Provocation",
  "Eruption",
  "Membrane",
  "NSAIDs",
  "Vaccinated",
  "Instructor",
  "Jargon",
  "Shin of tibia",
  "Chin of the face",
  "Pigment",
  "Detached retina",
  "Attached",
  "Glance",
  "Eye floaters",
  "Stretch marks",
  "Diaphragm",
  "Diaphoresis",
  "Low protein",
  "Rigidity",
  "Trauma after bicycle",
  "High protein",
  "Divorce",
  "Oily",
  "Yellow",
  "Vitamin A",
  "Statins or Statin",
  "Coronary artery",
  "Free protein",
  "Rapid pulse",
  "Hyperactive thyroid",
  "Reactive thyroid",
  "Vitamin K deficiency",
  "Burn",
  "Sling",
  "Spinehead",
  "Vivid flashbacks",
  "Vertical holes",
  "Dressmaker",
  "Central gap",
  "Polio",
  "Falling from a bicycle",
  "Right collarbone",
  "Chief",
  "Training in woman club",
  "Dry and cracked",
  "Cold sore",
  "Chopped lip",
  "Nightmare",
  "Partial complex",
  "Shut mind",
  "Sites",
  "Caltrate Plus D",
  "Lunesta",
  "Morphine Sulphate",
  "Zolpidem Tartrate",
  "Dilaudid",
  "L thyroxine",
  "Celestone Soluspan",
  "Vioxx",
  "Clindinium",
  "Chippy",
  "Choppy",
  "Watch and wait",
  "Acupressure",
  "Aerobic",
  "Anti-sickness",
  "Arthroplasty",
  "Arthroscopy",
  "District nurse",
  "Forklift driver",
  "Benadryl",
  "Bereavement counselling",
  "Osteopathy",
  "Bladder washout",
  "Phlebotomist",
  "Ceasing",
  "Cessation",
  "Codman-Hakim shunt",
  "Colposuspension",
  "Truck driver",
  "Crestor",
  "Tricor",
  "Sudafed",
  "Diseases",
  "Cymbalta",
  "Dentures",
  "Capsulitis",
  "Cervicitis",
  "Elastoplast",
  "Dust mite",
  "Excedrin",
  "Exploratory laparotomy",
  "Eczematous",
  "Floradix",
  "Fortnight",
  "Fortnightly",
  "Mastoiditis",
  "Head pad",
  "Heat pad",
  "Heating pad",
  "Palsy",
  "Lisinopril",
  "Pravastatin",
  "Diltiazem",
  "Hydrocodone",
  "Pedal oedema",
  "Illicit substances",
  "Petechiae",
  "Lorazepam",
  "Diphenhydramine",
  "Betamethasone",
  "Stress urinary incontinence",
  "Duloxetine",
  "Epinephrine",
  "Painkiller",
  "IVC filter",
  "Laminectomy",
  "Testicular torsion",
  "Testicle torsion",
  "Lipitor",
  "Losec",
  "Lovaza",
  "Lukewarm bath",
  "Sports",
  "Activities",
  "Macrogol",
  "Mastoidectomy",
  "Microdiscectomy",
  "Microdecompression",
  "Morning after pills",
  "Monofeme",
  "Orienteering",
  "Competition",
  "Tap dancing",
  "Gardening",
  "Nexium",
  "Lawn",
  "Mowing",
  "Oil moisturiser",
  "Toprol",
  "Zetia",
  "Playing darts",
  "Rackets",
  "Rock climbing",
  "Skier",
  "Pillow",
  "Pillow cases",
  "Half squat",
  "Prevnar vaccine",
  "Puffer",
  "Purgatives",
  "Aperients",
  "Sensations",
  "Feelings",
  "Fuzzy baby",
  "Fuzzy ear",
  "Fuzzy vision",
  "Off leash feeling",
  "Limp",
  "Supple neck",
  "Simethicone",
  "Sling for shoulder",
  "Alignment",
  "Misalignment",
  "Awkward",
  "Sotalol",
  "Band-like pressure",
  "Soup",
  "Soup substitute",
  "Loperamide",
  "Cefalexin",
  "Clonazepam",
  "Atorvastatin",
  "Gabapentin",
  "Celecoxib",
  "Amiodarone",
  "Pneumococcal vaccine",
  "Finasteride",
  "Black specks in urine",
  "Black specks in stool",
  "Strips",
  "Phobia",
  "Desk job",
  "Freelancer",
  "Weight loss",
  "Driver instructor",
  "Pounding",
  "Resistant breathing",
  "ANA",
  "Clicking noise",
  "Feverish",
  "Purple colour",
  "Eyes energy",
  "Shin bone",
  "Sex drive",
  "Grasses",
  "Stretching band",
  "Speech",
  "Lymph node biopsy",
  "Constrictive veins",
  "Earaches",
  "Multivitamins",
  "B12",
  "Purple",
  "Blenching",
  "Bubbling",
  "Rice Krispies",
  "Sizzling sound in ear",
  "Symbicort",
  "Budesonide",
  "Formoterol",
  "Bullet in the head",
  "Tummy tuck",
  "Abdominoplasty",
  "Skin bumps",
  "Ventolin",
  "Wheelie walker",
  "Rollator",
  "Xanax",
  "Alprazolam",
  "Cannot grip things",
  "Zantac",
  "Cetirizine",
  "Valium",
  "Chapped mouth",
  "Panadeine forte",
  "Chest pain like a strained or pulled muscle",
  "Colicky",
  "Bingeing",
  "Binge",
  "Concomitant",
  "Coconut",
  "Coryzal symptoms",
  "Grumpy",
  "Fizzy drinks",
  "Crescendo-decrescendo",
  "Deaf",
  "Dumb",
  "Mute",
  "Muteness",
  "Mutism",
  "Little and often regime",
  "Diseased",
  "Deceased",
  "Spells",
  "Dreadful",
  "Feeling little off or up & down",
  "Triticale",
  "Feeling rundown",
  "Whisky",
  "Weary",
  "Weariness",
  "Feeling weary",
  "Trembly",
  "Tremble",
  "Cardiotocograph",
  "Flabby arms",
  "Flabby abdomen",
  "Flashing lights",
  "Floppy baby",
  "Dietary counselling",
  "Grit in eyes",
  "Sertraline",
  "Husky voice",
  "Proctoscopy",
  "Punch biopsy",
  "Impingement",
  "Scintillation",
  "Achilles heel",
  "Moody",
  "Knee cap",
  "Nicked skin",
  "Nose stuffiness",
  "Stuffy nose",
  "Scrotal",
  "Pins, numbness and needles sensation",
  "Urethral",
  "Pounding headache",
  "Pounding heart",
  "Pounding ear",
  "Pounding pressure",
  "White of the eye",
  "Pulling sensation",
  "Other",
  "Rubbing eyes",
  "Abrupt",
  "Rumbling sound in abdomen",
  "Seeing floaters",
  "Bear weight",
  "Splitting",
  "Stomach feels full up",
  "Halved",
  "Intuitive",
  "Counter intuitive",
  "Mind-bending",
  "Suffocating",
  "Choke",
  "Strangle",
  "Asphyxiate",
  "Smother",
  "Stifle",
  "Nearly",
  "Tingle",
  "Tiredness",
  "Rigour",
  "Rigorous",
  "Twinging",
  "Tightness pain",
  "Stricter",
  "Urine sample",
  "Eye test",
  "Compulsive",
  "Heart rhythm",
  "Prenatal",
  "Crown rump length",
  "US",
  "Gestational age",
  "Compression packs",
  "O2 therapy",
  "Lucentis injection",
  "Non stitching",
  "Get bruises easily",
  "Impaired",
  "Amsler chart",
  "Distant sight",
  "Coversyl",
  "More light",
  "Uncle",
  "Senior",
  "Retinal clinic",
  "Meridian",
  "Ballet",
  "Niece",
  "Professional counsellor",
  "Mediterranean sea anaemia",
  "Obstructive",
  "Stress ECG",
  "Wellbeing",
  "Sylvian aqueduct",
  "DEXA",
  "On and off",
  "Radioallergosorbent",
  "Epididymitis",
  "Presbyopia",
  "Fiberoptic nasopharyngography",
  "Chronicus",
  "Risotto",
  "Brussels sprouts",
  "Norvasc",
  "Near sighted",
  "Ptosis",
  "Steatorrhoea",
  "Tenormin",
  "Cripple",
  "Oesophagogastroduodenoscopy",
  "Moaned",
  "Wheat intolerance",
  "Scheme instructor",
  "Hypnotherapy",
  "Extreme fear",
  "Wrist joints",
  "Software design",
  "Troponin",
  "Soft",
  "Thinning",
  "Jabbing pain",
  "Coordinator",
  "Tremors",
  "Aura",
  "Dripping",
  "Intermittent pain in jaw",
  "Fracture of sternum",
  "Socialised",
  "Sharp pain",
  "knives",
  "melfoquine",
  "thalassemia",
  "child care assistant",
  "extensive food allergy test",
  "bald patches",
  "Carpal tunnel",
  "dysponea",
  "waddling gait",
  "septicemia",
  "clogged ear",
  "rheumatoid",
  "trendelenburg gait",
  "Restless legs",
  "clogged nose",
  "weepy eye",
  "juvenile rheumatic arthritis",
  "fluoxetine antidepressant",
  "Accupuncture",
  "Acute",
  "Anaemic",
  "Analgesic",
  "Anus",
  "Autoimmune disorder",
  "Bad tempered",
  "Bald",
  "Balloon",
  "Blood",
  "Booster",
  "Catheterisation",
  "Chard",
  "Chemical therapy",
  "Chronic",
  "Cirrosis",
  "Cold compresses",
  "Colour",
  "Complication",
  "Conscious",
  "Cream",
  "Diet-free",
  "Dietitian",
  "Distance",
  "Drooping eyelids",
  "Duodenal cancer",
  "Eclampsia",
  "Examination",
  "Exercise therapy",
  "Expansion",
  "Fall",
  "Fat-free diet",
  "Fitful sleep",
  "Fractured",
  "Free",
  "Free diet",
  "Gas",
  "Gensing",
  "Hair",
  "Heart rate",
  "Hemochromatosis",
  "High",
  "Impact sports",
  "Involuntary movement",
  "Irregular",
  "Judge",
  "Juggling",
  "Large prostate",
  "Left-handed",
  "Libido",
  "Longstanding condition",
  "Low",
  "Lunchtime",
  "Lung",
  "Midwife",
  "Mouth",
  "Muscle dystrophy",
  "Need baby",
  "Nerve simulator",
  "Organiser",
  "Pelvic",
  "Pilling skin",
  "Plenty",
  "Position",
  "Post",
  "Pre",
  "Prediabetes",
  "Preventative",
  "Pulsing ablation",
  "Reactive protein",
  "Rib",
  "Ribcage",
  "Sales",
  "Scarlet",
  "Sensation",
  "Skin",
  "Spider palms",
  "Spine",
  "Stage",
  "Swollen ankles",
  "Syndrome",
  "Tempered",
  "Texture",
  "Threatening",
  "Thyroid test",
  "Tonic",
  "Uterine",
  "Vaccine",
  "Vitamin B",
  "Waking",
  "Whooping",
  "Abdominal",
  "Acromioclavicular",
  "Active",
  "Allergies",
  "Amino",
  "Amount",
  "Anaesthetic",
  "Anorexia",
  "Another",
  "Anticoagulant",
  "Antiseptic",
  "Artificial intelligence",
  "Assume",
  "Attacks",
  "Avoid",
  "Axillary",
  "Baby",
  "Bad",
  "Balanced diet",
  "Bank",
  "Base",
  "Basket",
  "Beats",
  "Beauty",
  "Bed wetting",
  "Bees",
  "Before",
  "Bending",
  "Bit",
  "Blocked ear",
  "Blockers",
  "Blood issues",
  "Bone Marrow",
  "Both",
  "Box",
  "Brain tumour",
  "Breast",
  "Bring",
  "Broken",
  "Bronchial",
  "Bronchial carcinoma",
  "Bronchiectasis",
  "Bulky",
  "Bulky muscle",
  "Bunch",
  "Caltrate",
  "Campylobacter",
  "Carbohydrate",
  "Carcinoma",
  "Card",
  "Case",
  "Celestone",
  "Centre",
  "Cervical",
  "Chair",
  "Cheek",
  "Childcare",
  "Childhood",
  "Ckd",
  "Clarify",
  "Classification",
  "Clonic",
  "Cloth",
  "Coeliac",
  "Cognitive therapy",
  "Cognitive function",
  "Collapse",
  "Colon",
  "Coming",
  "Common diagnosis",
  "Compartment",
  "Complex",
  "Compression",
  "Compressor",
  "Condition",
  "Consultation",
  "Convenience",
  "Corticosteroid",
  "Coughing",
  "Countries",
  "Cricking sound",
  "Crohn's",
  "Crutches type",
  "Cut",
  "Definition",
  "Degeneration",
  "Dermatology",
  "Described",
  "Developer",
  "Dietary advice",
  "Difficulties",
  "Disk prolapse",
  "Disoriented",
  "Diverticulitis",
  "Doing",
  "Drip",
  "Effects",
  "Electro immobilisation",
  "Embolism",
  "Empathy",
  "Environmental",
  "Ethics",
  "Excessive",
  "Facial droop",
  "Familiar",
  "Fast",
  "Fat",
  "Feeding",
  "Felt down",
  "Fenofibrate",
  "Fine texture",
  "Fish",
  "Fluid-filled blisters",
  "Following",
  "Food",
  "Frame",
  "Freelancer writer",
  "Freezing",
  "Full count",
  "Function",
  "Further investigation",
  "Fusidic acid",
  "Gastroenterologist",
  "Gels",
  "General",
  "Gluten intolerance",
  "Graded",
  "Greater",
  "Growing",
  "Haemorrhage",
  "Half hour",
  "Hand writing",
  "Hands",
  "Hay",
  "Heart burn",
  "Heel fracture",
  "Haematuria",
  "Herbal",
  "High pressure",
  "High-impact",
  "High-need",
  "Highlight",
  "Hip lump",
  "History",
  "Hormonal",
  "Housework",
  "Hygienist",
  "Immune therapy",
  "Insertional",
  "Irritate",
  "Jewellery",
  "Job",
  "Junk",
  "Juvenile",
  "Kicking",
  "Lapse",
  "Largely",
  "Left heel",
  "Life",
  "Lift weight",
  "Limbs",
  "Listless",
  "Long-standing",
  "Losing",
  "Lotion",
  "Low energy",
  "Lower",
  "Lying",
  "Machine",
  "Malerone tablets",
  "Malignancy",
  "Manager",
  "Market researcher",
  "Massage instructor",
  "Mattress",
  "Mean",
  "Meaning",
  "Meant",
  "Measure",
  "Measurement",
  "Memory loss",
  "Meniscus tear",
  "Mental illness",
  "Mild stroke",
  "Mindfulness",
  "Monitoring",
  "More than 50 hours",
  "Mosquitoes",
  "Mucolytic",
  "Multi organ failure",
  "Multi vitamin",
  "Ménière's",
  "Nasal packing",
  "Nerve block injection",
  "Nervous",
  "Neurology",
  "Neuroma",
  "Nose",
  "Nurse",
  "Nutrients",
  "Nutrition",
  "Occupational consultant",
  "Off",
  "Oral",
  "Over",
  "Pack",
  "Paints",
  "Pale",
  "Palm",
  "Palmoplantar",
  "Pancreatic",
  "Parameters",
  "Parvovirus",
  "Patchy inflamed",
  "Patient",
  "Physical therapy",
  "Physiotherapist",
  "Piece",
  "Pitting",
  "Plus",
  "Poisoning",
  "Poor hygiene",
  "Possibly",
  "Pounding head",
  "Precaution",
  "Premature ablation",
  "Present",
  "Preventive",
  "Primary",
  "Procedure",
  "Prostatic",
  "Pulmonary",
  "Pulmonologist",
  "Pulse",
  "Qualities",
  "Racing heart",
  "Raynaud's",
  "Reading",
  "Red toe",
  "Referring",
  "Reflex",
  "Relaxant",
  "Rely",
  "Remember",
  "Remembered",
  "Replacement",
  "Research study",
  "Respiratory",
  "Restless leg",
  "Restraint",
  "Restricted",
  "Retention",
  "Rheumatic",
  "Rhinocort",
  "Right ear",
  "Right thigh",
  "Right wrist",
  "Rubbing",
  "Saline",
  "School",
  "Sea",
  "Sedentary",
  "Senna laxatives",
  "Shake",
  "Shampoo",
  "Shivery",
  "Shockwave",
  "Sides",
  "Sinus",
  "Skin biopsy",
  "Sleeping pills",
  "Slightly",
  "Sloped",
  "Small",
  "Software",
  "Soluspan",
  "Something else",
  "Spasmodic",
  "Specimen",
  "Spinal tap",
  "Stationary",
  "Step up",
  "Stop",
  "Straps",
  "Sudden feeling",
  "Supplements",
  "Supraspinatus",
  "Suspected",
  "Sweats",
  "Syndromes",
  "Systematic steroid",
  "Systemic",
  "Talking",
  "Tape",
  "Tarsal",
  "Tennis",
  "Text",
  "Thin",
  "Thinners",
  "Thumbs",
  "Thump",
  "Tibia",
  "Tones",
  "Tonic clonic partial",
  "Topical",
  "Tough",
  "Trochanteric",
  "Tunnel",
  "Twin",
  "Twisted",
  "Under 18",
  "Underactive",
  "Upstairs",
  "Urethra dilation",
  "Urgent",
  "Urinary system",
  "Venous",
  "Very",
  "Veterinarian",
  "Vibrates",
  "Virus",
  "Visual",
  "Vitamin",
  "VNS",
  "Wait",
  "Walking",
  "Watch",
  "Waved",
  "Wax",
  "Web",
  "Weights",
  "Whiplash accidents",
  "Whipple",
  "Withdrawal",
  "Women's club",
  "Worrying",
  "Wrist splint",
  "Yoga classes",
  "Zika",
  "AF",
  "Agony pain",
  "Amino acids",
  "Anti-allergy drug",
  "Anti-depressants",
  "Anti-histamine",
  "Anti-septic",
  "Bald spots",
  "Bowel cancer",
  "Calamine",
  "Cloudiness",
  "Colonic",
  "Coronary artery disease",
  "Drawn",
  "Elastic bands",
  "Free blisters",
  "Glandular",
  "Icepacks",
  "Ketogenic diet",
  "Omega",
  "Paler",
  "Pannus",
  "Pin and needle",
  "Post-nasal drip",
  "Squat",
  "Therapy"
];
