window.OET_WORDS = [
    "Heat pack",
  "Breathless",
  "Cod Liver oil",
  "Bruise",
  "Clingy",
  "Bruising",
  "Bad constipation",
  "Headaches",
  "Dairy issue",
  "Constipated",
  "Oat",
  "Fidgety",
  "Wave hands",
  "Vitamin B6",
  "Twin sister",
  "Typing speed",
  "Exhausted",
  "Keyboard",
  "Grabbing",
  "Drenching",
  "Web designer",
  "Driving license",
  "Different food",
  "Bread",
  "Fish oil",
  "Chocolate period",
  "Flat",
  "Civil engineer",
  "Chubby",
  "Rashes",
  "Lifting",
  "Judge distance",
  "Falls",
  "Darker",
  "Hiking",
  "Blind",
  "Dust",
  "Occupation",
  "Ticket collector",
  "Type 1 diabetes",
  "Interpersonal Therapy",
  "B12 deficiency",
  "Periods",
  "Chocolate",
  "Hand",
  "CVS",
  "Siblings",
  "Dribbling",
  "flight attendant",
  "speech impairment",
  "irritable",
  "sticky",
  "lawyer",
  "constricted veins",
  "cold compress",
  "eye drops",
  "panic attacks",
  "heat packs",
  "software developer",
  "watery",
  "presentation",
  "wedding",
  "tennis ball",
  "surveyor",
  "basketball",
  "market research",
  "badly taste",
  "sharp",
  "university lecturer",
  "oesophageal cancer",
  "gluten-free",
  "thighs",
  "programmer",
  "herbal oil",
  "Impaction",
  "building sites",
  "sway",
  "dancing instructor",
  "died",
  "jump",
  "goalkeeper",
  "bent",
  "knife and fork",
  "Japan",
  "events manager",
  "fuzzy",
  "some sort of food",
  "magazine editor",
  "lung expansion",
  "asking",
  "full blood count",
  "swollen",
  "infection",
  "clockwise",
  "baggage",
  "savoury",
  "dragging",
  "spider",
  "sales manager",
  "meat",
  "oranges",
  "lemonades",
  "temper",
  "magnesium",
  "widow",
  "left tibia",
  "knife",
  "knives",
  "self-catheterisation",
  "Zika virus",
  "specialised message",
  "many strokes",
  "mouth ulcer",
  "anti-clockwise",
  "PPI (proton pump inhibitors)",
  "above normal",
  "occupational therapist",
  "volvulus",
  "meniscectomy",
  "toenail",
  "patella",
  "losartan",
  "romberg test",
  "chemical cauterisation",
  "aqueous gel",
  "scurvy",
  "clammy",
  "loose stool",
  "oral antibiotics",
  "Tendonitis",
  "sensitivity",
  "Torn ligament",
  "disc prolapse",
  "decongestant",
  "health check-up",
  "Sleepless",
  "freezing gait",
  "graft",
  "Wheezy",
  "ativan",
  "cardiotocography",
  "appendix",
  "gluten-free diet",
  "labourer",
  "Oral contraceptive",
  "miscarriage",
  "brainstem",
  "Collarbone",
  "bouncing sounds",
  "impairment",
  "oral medications",
  "blood clots",
  "insect repellent",
  "Stye",
  "metformin",
  "swollen ankle",
  "appendicectomy",
  "refined food",
  "nephrectomy",
  "flossing teeth",
  "stripping technique",
  "pigments in retina",
  "schizophrenia",
  "exacerbate",
  "fractured rib",
  "floating",
  "ineffective",
  "bruises",
  "mitomycin",
  "strain",
  "journalist",
  "blurred",
  "canker sores",
  "tamoxifen",
  "maternity",
  "amniocentesis",
  "athlete",
  "obstetrician",
  "Blisters",
  "pallor",
  "dermatologist",
  "acute inflammation",
  "barley",
  "synthroid",
  "cerebral palsy",
  "mental well-being",
  "dry cough",
  "C-reactive protein",
  "nocturia",
  "stung",
  "recurring lung infection",
  "precocious puberty",
  "rye",
  "substance abuse",
  "flurbiprofen",
  "Penicillin",
  "call centre",
  "bending over",
  "perfumed",
  "mental orphanage",
  "haemoglobin",
  "ritalin",
  "imodium",
  "melfoquine",
  "addictive",
  "cortisone cream",
  "piercing headache",
  "obstructive shock",
  "constricted",
  "high-impact sport",
  "conjunctival",
  "carotid Doppler",
  "Alzheimer's disease",
  "abnormalities",
  "Shellfish",
  "Cortisone injection",
  "burnout",
  "Bump on head",
  "amniotic level",
  "left thumb",
  "contraception",
  "Suprapubic catheter",
  "alternative therapy",
  "mammogram",
  "multivitamin",
  "excruciated",
  "zyrtec",
  "high fever",
  "BOSU ball",
  "blurring of vision",
  "eruption",
  "Internal nasal packing",
  "pethidine",
  "prilosec",
  "frequently",
  "knotted sensation",
  "convenient foods",
  "scarring",
  "flickering",
  "styes",
  "sensitive to light",
  "barium enema",
  "thalassemia",
  "hair grain",
  "Massage",
  "striking",
  "jewellery maker",
  "colposcopy",
  "photophobia",
  "combination of treatment",
  "rupture",
  "Pulsing",
  "opiate mix",
  "restricted diet",
  "burrow",
  "reflux",
  "typhoid fever",
  "ace inhibitors",
  "Ligaments",
  "nocturnal",
  "PET scan",
  "clumps",
  "transposition of great vessels",
  "crackling sound",
  "Thick",
  "frozen egg",
  "Palms",
  "mucofen",
  "noticeable",
  "motrin",
  "neonate",
  "myopia",
  "lean meat",
  "stingy",
  "administration via a pump",
  "HIV test",
  "splenectomy",
  "bent knee",
  "ophthalmologist",
  "pre-eclampsia",
  "crackling my knuckles",
  "hacking",
  "Chiropractic",
  "Eczema",
  "hydroquinone",
  "avelox",
  "furosemide",
  "free beta-hcg",
  "airway device",
  "electrolytes",
  "child care assistant",
  "ventilator",
  "deafness",
  "punctured lung",
  "moisturiser",
  "Bladder spasm",
  "prone",
  "loss of memory",
  "chloroquine",
  "Crohn's disease",
  "Botox injection",
  "murmur",
  "analgesic cream",
  "heparin injections",
  "verapamil",
  "bone marrow biopsy",
  "stationary life",
  "ejection fraction",
  "Teeth",
  "prolactin",
  "Muscle tone",
  "blue limbs",
  "cricking",
  "Purple rash",
  "High-fiber diet",
  "gastric flu",
  "cholangiogram",
  "humidifier",
  "extensive food allergy test",
  "wheat",
  "ventilation",
  "Discharge",
  "peppermint oil",
  "malignant",
  "auditory",
  "breech",
  "distorted",
  "septoplasty",
  "viral myocarditis",
  "enlarged prostate",
  "blurred vision",
  "Soreness",
  "cannabis",
  "athletic",
  "coronary stent",
  "labetalol",
  "measles",
  "Saline drip",
  "torsion",
  "PSA",
  "CT scan",
  "vascular dementia",
  "wasp sting",
  "dry mouth",
  "leaking valve",
  "antiviral cream",
  "nordic walking",
  "short-sighted",
  "stuttered",
  "sticky eyes",
  "bald patches",
  "maternal screening",
  "tearing",
  "Acoustic neuroma",
  "Carpal tunnel",
  "hydrochlorothiazide",
  "cirrhosis",
  "deviated septum",
  "dysponea",
  "kidney transplant",
  "Smelling",
  "miscarriages",
  "ecstasy",
  "shooting",
  "narcissistic personality disorder",
  "intense burning",
  "end-stage renal failure",
  "lumbar lordosis",
  "care assistant",
  "brown marks",
  "Meniere's disease",
  "armpit",
  "senna tablets",
  "stiff feeling in neck",
  "excessive exercise",
  "Co-codamol",
  "longstanding",
  "legumes",
  "prednisolone",
  "amoebic dysentery",
  "kidney graft",
  "osteopathic chair",
  "waddling gait",
  "Immune disorder",
  "tetanus vaccine",
  "hereditary spherocytosis",
  "omeprazole",
  "electrical impulse",
  "doxycycline",
  "graded exercise therapy",
  "flat position",
  "bone grafting",
  "hormonal imbalance",
  "flare-up of scratchy",
  "meningococcal",
  "advair diskus",
  "bilirubin",
  "herpes simplex",
  "Spiders",
  "duodenal ulcer",
  "handrails",
  "barium meal",
  "twisted disc",
  "paediatrician",
  "coagulation profile",
  "odontalgia",
  "clindinium",
  "lupus groin",
  "thyroxine",
  "short-sightedness",
  "irritable bowel syndrome",
  "dry crackers",
  "liquid morphine",
  "induced coma",
  "Superior aspect",
  "jet lag",
  "Lumps",
  "BMD test",
  "iron deficiency anaemia",
  "zoloft",
  "loosened stool",
  "shin of tibia",
  "daptomycin",
  "Heparin",
  "high-fibre diet",
  "deteriorate",
  "transvaginal ultrasound",
  "Transfusion",
  "skin tag",
  "right thumb",
  "decaffeinated",
  "pain relief",
  "lightheadedness",
  "abdominal girth",
  "tension headaches",
  "NSAIDs",
  "left buttock",
  "condom",
  "Forceps",
  "MRI",
  "vibrating tool",
  "scarlet fever",
  "contact lens",
  "rhinocort nasal spray",
  "car accident",
  "trapped nerve",
  "MDMA",
  "Lying flat",
  "X-ray",
  "constipation",
  "infertility",
  "anaesthesia",
  "dizzy spells",
  "gastrectomy",
  "frontal lobe",
  "Petechial rash",
  "stomach pain",
  "adhesive",
  "masticatory muscle",
  "irritated skin",
  "weight gain",
  "amoxicillin",
  "environmental engineering",
  "knee clicking",
  "breakthrough pain",
  "skin rash",
  "Glucosamine",
  "leafy green",
  "warm compress",
  "hospitalisation",
  "Groggy",
  "Administrator",
  "proscar",
  "lean body",
  "slipped disc",
  "peritonitis",
  "glue ear",
  "Bell's palsy",
  "bulging out",
  "plaque",
  "allergic contact dermatitis",
  "right knee",
  "PPI",
  "dengue fever",
  "epipen",
  "sperm",
  "muscle relaxants",
  "soothing ointment",
  "jarring injury",
  "psychological assessment",
  "treadmill",
  "left ventricle",
  "absorb",
  "klonopin",
  "strengthening exercises",
  "sinus inflammation",
  "seborrhoeic dermatitis",
  "plavix",
  "hair loss",
  "petroleum jelly",
  "rigid contacts",
  "Superior area",
  "xerostomia",
  "down gaze",
  "inhibin A",
  "Pelvic adhesions",
  "Parkinson's disease",
  "fetoprotein",
  "struvite stone",
  "Gripping",
  "dumbbells",
  "lockjaw",
  "Intravenous therapy",
  "Ibuprofen",
  "septicemia",
  "anaemia",
  "Electroencephalogram",
  "an underactive thyroid",
  "blurring",
  "spotting",
  "optometrist",
  "BRCA",
  "stabbing",
  "bouts of vomiting",
  "gum lump",
  "Ablation",
  "festinating gait",
  "mechanical ventilatory support",
  "spleen",
  "Stutter",
  "nutritionist",
  "cholesterol level",
  "prednisone",
  "absence seizure",
  "hand splints",
  "nostril",
  "hypermetropia",
  "bloating sensation",
  "high-impact sports",
  "Muscular dystrophy",
  "elevation",
  "Tonic-clonic",
  "malarone tablets",
  "elbow creases",
  "regurgitation",
  "lice comb",
  "pelvic inflammatory disease",
  "Acne",
  "dental assistant",
  "tarsal fracture",
  "crippled",
  "bereavement",
  "slurring speech",
  "bum cheek",
  "hypothyroidism",
  "massage therapist",
  "asthmatic inhalers",
  "lumpectomy",
  "fibres",
  "ketones",
  "Ointment",
  "lichen simplex",
  "reading glasses",
  "Apnoea",
  "preventative medicine",
  "flu",
  "antibiotic",
  "throbbing pain",
  "diet free of gluten",
  "platelets",
  "clogged ear",
  "cloudy",
  "warm compression",
  "growth spurt",
  "cracking sound",
  "tummy pain",
  "microkeratome",
  "stuttering",
  "horizontal gaze",
  "Sphincter",
  "Neck pain",
  "paediatric dentist",
  "Crusting",
  "lying flat position",
  "supine",
  "eases",
  "embolisation",
  "Resistance band",
  "aggressive",
  "carvedilol",
  "concentration",
  "gestational diabetes",
  "uterine balloon",
  "cramping",
  "giardia",
  "lukewarm",
  "aspiration",
  "fingernails",
  "fractures",
  "low-fat diet",
  "antalgic gait",
  "swallowing difficulty",
  "aspirin",
  "steroid tablet",
  "dermatitis",
  "immobilisation boot",
  "processed meat",
  "phlegm",
  "common cold",
  "elbow",
  "infarcts",
  "shockwave surgery",
  "sides of buttocks",
  "tingling sensation",
  "periodontal disease",
  "frequent",
  "rheumatoid",
  "primaxin",
  "additional tests",
  "General anaesthesia",
  "atacand",
  "concussions",
  "bone loss in jaw",
  "multiple organ failure",
  "CBT",
  "netball",
  "amnesia",
  "OTC",
  "in concentration",
  "cystoprostatectomy",
  "flaky",
  "malabsorption",
  "psychiatrist",
  "bracing",
  "wisdom teeth",
  "bump his head",
  "Self-harm",
  "fibre",
  "corticosteroid injection",
  "left thigh",
  "losing weight",
  "brace",
  "liver cancer",
  "prenatal bruising",
  "trendelenburg gait",
  "tongue-tie",
  "abstain",
  "visual perception",
  "Stretch",
  "gastric dumping syndrome",
  "dental caries or decay",
  "Loss of appetite",
  "Restless legs",
  "clogged nose",
  "life-threatening",
  "gingivitis",
  "Strapping",
  "macular degeneration",
  "anti-inflammatories",
  "prolapsing",
  "LASIK surgery",
  "fallopian tubes",
  "kinesiologist",
  "levaquin",
  "abdominal rigidity",
  "malarone",
  "Tremor",
  "weepy eye",
  "jerking movements",
  "craving",
  "body parts",
  "uncomfortable stomach",
  "juvenile rheumatic arthritis",
  "wart",
  "booster injection",
  "Arthritis",
  "fluoxetine antidepressant",
  "poliovirus",
  "cystourethroscopy",
  "ocD",
  "waviness in reading",
  "compression stockings",
  "ECG",
  "sprain ankle",
  "diabetic retinopathy",
  "croup",
  "Urethral dilation",
  "Electrotherapy",
  "Gastric reflux",
  "oedema",
  "Therapist",
  "twitch",
  "accountant",
  "autism",
  "debilitated",
  "dysfunctional",
  "floppy",
  "D-dimer",
  "albuterol",
  "Abdomen",
  "Abdominal area",
  "Abdominal pain",
  "Absence seizures",
  "Accupuncture",
  "A CE inhibitors",
  "Achilles tendon",
  "Aching",
  "Acupuncture",
  "Acute",
  "Adhesion",
  "Aerobics",
  "Aerobic exercises",
  "Affection",
  "Agoraphobia",
  "Agitated",
  "Alcohol",
  "Allergy",
  "Allergy test",
  "Allopurinol",
  "Alzheimer’s",
  "Amino acid",
  "Ammonia",
  "Anaemic",
  "Anaerobic",
  "Anaesthetic medication",
  "Analgesic",
  "Aneurysm",
  "Anger",
  "Angina",
  "Ankle",
  "Ankles",
  "Anorexia nervosa",
  "Antacid",
  "Antacids",
  "Antidepressant",
  "Antifungal",
  "Antihistamine",
  "Antihistamines",
  "Anti-inflammatory",
  "Antiseptic shampoo",
  "Antisocial",
  "Antispasmodic",
  "Anus",
  "Anxiety",
  "Anxiety attack",
  "Anxiety attacks",
  "Anxious",
  "Appendectomy",
  "Appendicitis",
  "Appetite",
  "Arms",
  "Around ribs",
  "Asthma",
  "Astigmatism",
  "Atenolol",
  "Atrial fibrillation",
  "Attack",
  "Autoimmune",
  "Autoimmune disorder",
  "Awful",
  "Awareness",
  "Back",
  "Backhand",
  "Baclofen",
  "Badminton",
  "Badminton sport",
  "Bad odour",
  "Bad tempered",
  "Baggage handler",
  "Balance",
  "Bald",
  "Balloon",
  "Bandage",
  "Bank manager",
  "Bearable",
  "Beauty therapist",
  "Beeswax",
  "Beer",
  "Behaviour",
  "Beta blocker",
  "Beta blockers",
  "Bicycle",
  "Big toe",
  "Big toe arthritis",
  "Big toes",
  "Biopsy",
  "Bipolar",
  "Bitter",
  "Bitter taste",
  "Bladder",
  "Blindness",
  "Blinking",
  "Blister",
  "Blood",
  "Bloodshot",
  "Blood test",
  "Blood thinners",
  "Blood transfusion",
  "Blotches",
  "Blotchy",
  "Bloated",
  "Bloating",
  "Booster",
  "Botanist",
  "Botox",
  "Both calves",
  "Both knees",
  "Boxing",
  "Brain fog",
  "Brain scan",
  "Breakfast",
  "Breast cancer",
  "Breastfeed",
  "Breastfeeding",
  "Breathlessness",
  "Bronchitis",
  "Broken ribs",
  "Brownish",
  "Building inspector",
  "Bulimia",
  "Bump on the head",
  "Bumps",
  "Bunion",
  "Burning",
  "Burping",
  "Buzzing",
  "Calamine lotion",
  "Calcium",
  "Calf",
  "Calves",
  "Cancer",
  "Canal",
  "Carbohydrates",
  "Cardiologist",
  "Cardizem",
  "Carpal tunnel syndrome",
  "Carpenter",
  "Carer",
  "Catheterisation",
  "Cataract",
  "Cauterisation",
  "Celebrex",
  "Cellulitis",
  "Central nervous system",
  "Cervical cancer",
  "Change dressing",
  "Chard",
  "Cheeks",
  "Cheese",
  "Chef",
  "Chemical therapy",
  "Chemotherapy",
  "Chest",
  "Chest infection",
  "Chest pain",
  "Chest X-ray",
  "Chewing",
  "Chickenpox",
  "Chills",
  "Chins",
  "Chiropractor",
  "Chlordiazepoxide",
  "Choking",
  "Cholecystectomy",
  "Cholesterol",
  "Chronic",
  "Cirrosis",
  "Clavicle",
  "Cleaner",
  "Cleft lip",
  "Clicking",
  "Climbing stairs",
  "Climbing upstairs",
  "Clots",
  "Clothes",
  "Clumsy",
  "Coconut oil",
  "Codeine",
  "Cold compression",
  "Cold compresses",
  "Cold sores",
  "Cold water",
  "Colonoscopy",
  "Colostomy",
  "Colour",
  "Colouring",
  "Coma",
  "Commercial artist",
  "Complex partial",
  "Complication",
  "Compartment syndrome",
  "Compression socks",
  "Computer",
  "Computer programmer",
  "Concentrate",
  "Concussion",
  "Confidence",
  "Confusion",
  "Congested vein",
  "Conjunctivitis",
  "Conscious",
  "Constant pain",
  "Construction worker",
  "Contagious",
  "Contiguous",
  "Continence",
  "Convenience diet",
  "Convenience food",
  "Convulsions",
  "Coordination",
  "Cortisone",
  "Corticosteroids",
  "Cough",
  "Coughing fits",
  "Counselling",
  "Counsellor",
  "Cracked",
  "Cracked lips",
  "Crackling",
  "Crackling sounds",
  "Cramps",
  "Cranberry supplement",
  "Cream",
  "Cricket",
  "Crohn’s disease",
  "Crowded places",
  "Crutches",
  "Cry",
  "Crusty mucus",
  "Cut two fingers",
  "Cuts",
  "Cycling",
  "Cyclophosphamide",
  "Cystitis",
  "Cystoscopy",
  "Dairy",
  "Dairy products",
  "Dancing",
  "Dandruff",
  "Dark",
  "Dark red",
  "Dark red urine",
  "Dark urine",
  "Daughter",
  "Debilitating",
  "Deep vein thrombosis",
  "Deficiency",
  "Dehydrated",
  "Dehydration",
  "Dementia",
  "Dental hygienist",
  "Deodorant",
  "Depression",
  "Dermatology consultation",
  "Diabetes",
  "Dialysis",
  "Diarrhoea",
  "Diary",
  "Dietary",
  "Dietary issue",
  "Diet-free",
  "Dietitian",
  "Different",
  "Dilantin",
  "Discolouration",
  "Disease",
  "Disorientation",
  "Distance",
  "Distracted",
  "Dizziness",
  "Dog trainer",
  "Double vision",
  "Down syndrome",
  "Drained",
  "Dread",
  "Dressing",
  "Dribble",
  "Driving",
  "Driving instructor",
  "Drooping eyelid",
  "Drooping eyelids",
  "Droopy",
  "Drowsy",
  "Dry",
  "Duodenal cancer",
  "Dull ache",
  "Dyspepsia",
  "Earache",
  "Ear infection",
  "Ears",
  "Eating",
  "Echocardiogram",
  "Eclampsia",
  "Echo",
  "Elbow joint",
  "Electric shock",
  "Emotional",
  "Emotional outbursts",
  "Emphysema",
  "Endometriosis",
  "Energy",
  "Engineer",
  "Engineering",
  "Environmental engineer",
  "Epilepsy",
  "Ethanol",
  "Examination",
  "Exam",
  "Exhaustion",
  "Exercise",
  "Exercise straps",
  "Exercise therapy",
  "Expansion",
  "Eyelids",
  "Eyes",
  "Eyebrows",
  "Factory cleaner",
  "Fainting",
  "Faint",
  "Fall",
  "Fast food",
  "Fat-free diet",
  "Fatigue",
  "Febrile convulsion",
  "Fell",
  "Femur",
  "Ferritin",
  "Fertility",
  "Fertility treatment",
  "Fever",
  "Fibre diet",
  "Fibromyalgia",
  "Financial advisor",
  "Financial difficulties",
  "Financial problems",
  "Finances",
  "Fine",
  "Fingers",
  "Fingertips",
  "Firefighter",
  "Firefighters",
  "Fitness",
  "Fitful sleep",
  "Flagyl",
  "Flaky skin",
  "Flat mattress",
  "Flomax",
  "Fluid",
  "Fluids",
  "Flu vaccine",
  "Flu vaccination",
  "Food poisoning",
  "Four months",
  "Fracture",
  "Fractured",
  "Free",
  "Free diet",
  "Freeze",
  "Freelance journalist",
  "Gallbladder",
  "Gallstone",
  "Gallstones",
  "Gardener",
  "Garlic",
  "Garlic pills",
  "Gas",
  "Gastric bypass",
  "Gastric bypass surgery",
  "Gastroenterology",
  "Gentle exercise",
  "Gensing",
  "Ginseng",
  "Ginseng supplements",
  "Glandular fever",
  "Glaucoma",
  "Gluten",
  "Golf",
  "Gout",
  "Graded exercise",
  "Grain",
  "Grandmother",
  "Graphic designer",
  "Greasy",
  "Groin",
  "Groin area",
  "Growing pain",
  "Growing pains",
  "Guitar",
  "Gums",
  "Gymnastics",
  "Hair",
  "Hamstring",
  "Hand cream",
  "Handwriting",
  "Hay fever",
  "Headache",
  "Healthy",
  "Hearing loss",
  "Heartbeat",
  "Heartbeats",
  "Heartburn",
  "Heart murmur",
  "Heart rate",
  "Heat pads",
  "Heaviness",
  "Heavy",
  "Heavy lifting",
  "Heel",
  "Hemochromatosis",
  "Heparin injection",
  "Hepatitis",
  "Hernia",
  "High",
  "High blood pressure",
  "Hip",
  "Hip joint",
  "Hip replacement",
  "Hips",
  "Hives",
  "Hockey",
  "Holter monitor",
  "Homemaker",
  "Hopelessness",
  "Hot pads",
  "Housebound",
  "Housewife",
  "Hydralazine",
  "Hydrated",
  "Hydration",
  "Hydrocortisone",
  "Hypertension",
  "IBS",
  "Ice pack",
  "Ice packs",
  "Imitating",
  "Immune system",
  "Impact sports",
  "Incontinence",
  "Indigestion",
  "Indoor exercises",
  "Infertile",
  "Inflammation",
  "Inflammatory",
  "Inflamed",
  "Injection",
  "Injections",
  "Insomnia",
  "Intense",
  "Intermittent",
  "Intermittent catheter",
  "Involuntary movement",
  "Iron deficiency",
  "Iron-deficiency anaemia",
  "Irregular",
  "Irritable bowel",
  "Irritated",
  "Isolated",
  "Itching",
  "Itchy",
  "Itchy leg",
  "IV antibiotics",
  "Jabbing",
  "Jaundice",
  "Jaw",
  "Jaw exercise",
  "Jobbing",
  "Jogging",
  "Joint pain",
  "Joints",
  "Joints pain",
  "Judge",
  "Judo",
  "Juggling",
  "Junk food",
  "Juvenile rheumatoid arthritis",
  "Ketogenic",
  "Kidney",
  "Kidney cancer",
  "Kidney disease",
  "Kidney infection",
  "Kidney stone",
  "Kidney stones",
  "Knee",
  "Knee replacement",
  "Knees",
  "Ladder",
  "Laparoscopy",
  "Large prostate",
  "Laser",
  "Laughing",
  "Law",
  "Laxatives",
  "Left ankle",
  "Left calf",
  "Left knee",
  "Left leg",
  "Left ventricular hypertrophy",
  "Leathery",
  "Leathery skin",
  "Left-handed",
  "Leukaemia",
  "Lethargic",
  "Lethargy",
  "Levothyroxine",
  "Libido",
  "Lifting weights",
  "Light",
  "Light bleeding",
  "Lighter",
  "Limping",
  "Liposuction",
  "Liver",
  "Longstanding condition",
  "Loss of energy",
  "Loss of hearing",
  "Low",
  "Low fat",
  "Lower back",
  "Luggage",
  "Lump",
  "Lunch",
  "Lunch time",
  "Lunchtime",
  "Lung",
  "Lung cancer",
  "Lupus",
  "Lying down",
  "Lymph nodes",
  "Malaria",
  "Malaria tablets",
  "Management",
  "Meals",
  "Mechanic",
  "Melanoma",
  "Melatonin",
  "Memory",
  "Memory lapse",
  "Ménière’s disease",
  "Meningitis",
  "Menopause",
  "Menstruation",
  "Metal rod",
  "Metallic",
  "Metallic taste",
  "Methadone",
  "Midwife",
  "Mild fever",
  "Migraine",
  "Migraines",
  "Mini stroke",
  "Mononucleosis",
  "Mood swing",
  "Morphine",
  "Motivation",
  "Mouth",
  "Mouth ulcers",
  "Mouse",
  "Movement",
  "Multiple sclerosis",
  "Multiple system failure",
  "Mumps",
  "Muscle biopsy",
  "Muscle dystrophy",
  "Muscle relaxant",
  "Muscle tones",
  "Muscles",
  "Mushroom",
  "Nail",
  "Nasal spray",
  "Nausea",
  "Neck",
  "Need baby",
  "Needles",
  "Neighbour",
  "Neighbours",
  "Nephrologist",
  "Nerve simulator",
  "Neurontin",
  "Neurologist",
  "Nightmares",
  "Night sweats",
  "Nitroglycerin",
  "Normal",
  "Nosebleed",
  "Nosebleeds",
  "Numbness",
  "Nursery",
  "Oats",
  "Obesity",
  "Obese",
  "Office",
  "Oily fish",
  "Oil paints",
  "Opioid",
  "Opioids",
  "Optic disc",
  "Oral contraceptives",
  "Orange",
  "Organiser",
  "Osteoarthritis",
  "Osteomyelitis",
  "Osteoporosis",
  "Ovarian cysts",
  "Overactive thyroid",
  "Pacemaker",
  "Painkillers",
  "Palpitations",
  "Pancreatitis",
  "Panic",
  "Panic attack",
  "Paracetamol",
  "Paralysis",
  "Partial seizure",
  "Patchy",
  "Peanut",
  "Peanut allergy",
  "Pelvic",
  "Pelvic congestion",
  "Pelvic ultrasound",
  "Peppermint",
  "Perception",
  "Perfume",
  "Perfumes",
  "Permanent",
  "Persistent",
  "Personal trainer",
  "Physical activity",
  "Physiotherapy",
  "Physiotherapy session",
  "Piercing",
  "Pilling skin",
  "Pink eye",
  "Pink eyes",
  "Pins and needles",
  "Pituitary",
  "Pituitary MRI",
  "Playing squash",
  "Plenty",
  "Pleurisy",
  "Pneumonia",
  "Popping",
  "Popping sound",
  "Position",
  "Post",
  "Potassium",
  "Potassium level",
  "Pounding sound",
  "Pre",
  "Prediabetes",
  "Pregnancy",
  "Pressure",
  "Pressure sores",
  "Preventative",
  "Prevention",
  "Preventer",
  "Preventive measures",
  "Prickling",
  "Probiotic",
  "Project manager",
  "Propranolol",
  "Prostate cancer",
  "Prostatic cancer",
  "Protein",
  "Pruritus",
  "Psoriasis",
  "Psychological",
  "Puberty",
  "Pulmonary embolism",
  "Pulsing ablation",
  "Pus",
  "Radiation",
  "Radiotherapy",
  "Rash",
  "Reactive protein",
  "Red meat",
  "Red spots",
  "Reflexes",
  "Refreshed",
  "Regular",
  "Relief",
  "Repetitive nerve stimulation",
  "Repeat",
  "Respiratory infection",
  "Restless",
  "Restless at school",
  "Restless legs syndrome",
  "Rheumatic fever",
  "Rheumatology",
  "Rib",
  "Rib cage",
  "Ribcage",
  "Right shoulder",
  "Rivaroxaban",
  "Rods",
  "Rotator cuff",
  "Rubbing ointment",
  "Rubella",
  "Rugby",
  "Sailor",
  "Sailing",
  "Sales",
  "Salmonella",
  "Salad",
  "Scalp",
  "Scabbing",
  "Scabies",
  "Scar",
  "Scarlet",
  "Sciatica",
  "Scoliosis",
  "Scrotum",
  "Scuba diving",
  "Seafood",
  "Security guard",
  "Sedentary life",
  "Seizure",
  "Seizures",
  "Self confidence",
  "Sensation",
  "Sensitivity to light",
  "Sepsis",
  "Serious wrist fracture",
  "Shingles",
  "Shivering",
  "Shock",
  "Shooting pain",
  "Shooting sensation",
  "Short of breath",
  "Shoulder dystocia",
  "Shoulders",
  "Shower gels",
  "Sick and dizzy",
  "Simvastatin",
  "Sinuses",
  "Sinus infection",
  "Sinusitis",
  "Sitting down",
  "Skin",
  "Skin is dry and flaky",
  "Skin rashes",
  "Sleep apnoea",
  "Sleepiness",
  "Slurred",
  "Slurred speech",
  "Slow",
  "Smell",
  "Smoking",
  "Soap",
  "Soccer",
  "Social gathering",
  "Social gatherings",
  "Sodium",
  "Sodium bicarbonate",
  "Software designer",
  "Soles",
  "Sore throat",
  "Sour",
  "Sour taste",
  "Spasm",
  "Spasms",
  "Spider palms",
  "Spine",
  "Spirometry",
  "Spitting",
  "Spots",
  "Sprain",
  "Squat position",
  "Stage",
  "Stabbing pain",
  "Stairs",
  "Standing up",
  "Statin",
  "Steady",
  "Steroid",
  "Steroid cream",
  "Steroid injection",
  "Steroid injections",
  "Steroids",
  "Stiff",
  "Stiffened",
  "Stiff neck",
  "Stiffness",
  "Stinging",
  "Stoma",
  "Stomach",
  "Stomach ache",
  "Stomach cramps",
  "Stomach ulcer",
  "Strangulation",
  "Strawberry tongue",
  "Strength",
  "Stress",
  "Stretching",
  "Stroke",
  "Strong smells",
  "Sugar",
  "Swallow",
  "Swallowing",
  "Sweat",
  "Sweating",
  "Swelling",
  "Swelling up",
  "Swimming",
  "Swollen ankles",
  "Swollen tongue",
  "Syndrome",
  "Systemic lupus",
  "Systemic lupus erythematosus",
  "Tailor",
  "Tantrum",
  "Taste",
  "Tea",
  "Tea tree oil",
  "Teething",
  "Tempered",
  "Temperature",
  "Temporary blindness",
  "Tendinitis",
  "Tendon",
  "Testosterone",
  "Tetanus",
  "Tetanus vaccination",
  "Texture",
  "Thirsty",
  "Threatening",
  "Throat cancer",
  "Throat infection",
  "Throbbing",
  "Thumb",
  "Thymus gland",
  "Thyroid",
  "Thyroid disease",
  "Thyroid function",
  "Thyroid function test",
  "Thyroid test",
  "TIA",
  "Tiger balm",
  "Tightness",
  "Tingling",
  "Tinnitus",
  "Tired",
  "Toe",
  "Toes",
  "Tomatoes",
  "Tongue",
  "Tonic",
  "Tonsil",
  "Tonsillectomy",
  "Tonsillitis",
  "Tooth extraction",
  "Topical antibiotic",
  "Topical antibiotics",
  "Toys",
  "Traffic noise",
  "Training",
  "Trance",
  "Translator",
  "Transplant",
  "Traumatic",
  "Trembling",
  "Triptan",
  "Tumour markers",
  "Tummy ache",
  "Twisting",
  "Two toes",
  "Typically",
  "Ulcer",
  "Ulcerative colitis",
  "Ultrasound",
  "Underactive thyroid",
  "Uncooperative",
  "Unsteady",
  "Unsaturated fats",
  "Unsociable",
  "Upper limb",
  "Urgency",
  "Uric acid",
  "Urinalysis",
  "Urinating",
  "Urinary tract infection",
  "Urine retention",
  "Uterine",
  "Uterine balloon therapy",
  "Uterine cancer",
  "Vaccine",
  "Van driver",
  "Varicose veins",
  "Vascular",
  "Vegan",
  "Vegetables",
  "Vegetarian",
  "Vegetarian diet",
  "Vertigo",
  "Vibration",
  "Vibrating",
  "Vision",
  "Vitamin B",
  "Vitamin D",
  "Vitiligo",
  "Vocabulary",
  "Voice",
  "Vomited",
  "Vomiting",
  "Vomiting attacks",
  "VNS therapy",
  "Waking",
  "Walking frame",
  "Warehouse",
  "Warm compresses",
  "Washing hair",
  "Water",
  "Weakness",
  "Weight",
  "Weightlifting",
  "Weightlifter",
  "Wheezing",
  "Whiplash",
  "Whiplash injury",
  "White",
  "White crust",
  "White crusts",
  "Whooping",
  "Whooping cough",
  "Withdrawn",
  "Work",
  "Workaholic",
  "Wrist",
  "Wrist brace",
  "Wrist joint",
  "Wrists",
  "Yoga",
  "Yoga class",
  "Yoghurt",
  "Zinc",
  "Zolpidem",
  "16 mg",
  "Abdominal",
  "Acromioclavicular",
  "Active",
  "AF (atrial fibrillation)",
  "Allergies",
  "Alzheimer's",
  "Ambulance",
  "Amino",
  "Amount",
  "An appendicitis",
  "Anorexia",
  "Another",
  "Anterior nasal packing",
  "Antidepressants",
  "Antiseptic",
  "Apathy",
  "Artificial intelligence",
  "Assume",
  "Attacks",
  "Avoid",
  "Axillary",
  "B12",
  "Baby",
  "Bad",
  "Balanced diet",
  "Bank",
  "Base",
  "Basket",
  "Beats",
  "Bed wetting",
  "Bees wax",
  "Before",
  "Bend",
  "Biologist",
  "Bit",
  "Blocked ear",
  "Blockers",
  "Blood issues",
  "Bold",
  "Bold muscle",
  "Bone marrow",
  "Both",
  "Bout",
  "Box",
  "Brain tumour",
  "Breast",
  "Breastbone",
  "Bright sunlight",
  "Bring",
  "Broken",
  "Bronchial",
  "Bronchial carcinoma",
  "Bronchiectasis",
  "Builder",
  "Bump",
  "Bunch",
  "Burn",
  "Burning sensation",
  "Buttock",
  "Buttocks",
  "Caffeine",
  "Caltrate plus",
  "Campylobacter",
  "Carbohydrate",
  "Carcinoma",
  "Card",
  "Case",
  "Cauterization",
  "CBT (Cognitive Behavioural Therapy)",
  "Celestone soluspan",
  "Centre",
  "Cervical",
  "Cheek",
  "Chief",
  "Childcare",
  "Childhood",
  "Ckd",
  "Clarify",
  "Classification",
  "Clonic",
  "Clopidogrel",
  "Cloth",
  "Clouded",
  "Coeliac",
  "Cognitive function therapy",
  "Cold sore",
  "Collapse",
  "Colon",
  "Colonic",
  "Coming off",
  "Common diagnosis",
  "Compartment",
  "Complex",
  "Compression",
  "Compressor",
  "Condition",
  "Congestion",
  "Constant",
  "Consultation",
  "Continued",
  "Convenience",
  "Corticosteroid",
  "Coughing",
  "Countries",
  "Cricking sound",
  "Crohn's",
  "Crutches type",
  "Cut",
  "Definition",
  "Degeneration",
  "Dermatology",
  "Described",
  "Developer",
  "Dietary advice",
  "Difficulties",
  "Dilaudid",
  "Disk prolapse",
  "Disoriented",
  "Diverticulitis",
  "Dizzy",
  "Doing",
  "Dreadful",
  "Drill",
  "Drinking tea",
  "Drive",
  "Drooping",
  "Dry skin",
  "Effects",
  "Electroimmobilization",
  "Empathy",
  "Environmental",
  "Ethics",
  "Excessive",
  "Eyes surgery",
  "Facial droop",
  "Familiar",
  "Fast",
  "Fat",
  "Fatty meat",
  "Feeding",
  "Felt down",
  "Fenofibrate",
  "Fidget",
  "Financial",
  "Financial consultant",
  "Fine texture",
  "Fish",
  "Fitful",
  "Floaters",
  "Following",
  "Food",
  "Frame",
  "Free blisters",
  "Freelance writer",
  "Freelancer",
  "Freezing",
  "Frightening",
  "Full count",
  "Function",
  "Further investigation",
  "Fusidic acid",
  "Gastroenterologist",
  "Gels",
  "General anaesthetic",
  "Ginger",
  "Glue",
  "Gluten intolerance",
  "Graded",
  "Greater trochanteric",
  "Grip",
  "Grommet",
  "Growing",
  "Haematuria",
  "Haemorrhage",
  "Hairdresser",
  "Half hour",
  "Hammer",
  "Hands",
  "Hard",
  "Hay",
  "Hearing",
  "Heel fracture",
  "Heels",
  "Herbal",
  "Herbalist",
  "Hiatus hernia",
  "High pressure",
  "High-impact",
  "High-need",
  "Highlight",
  "Hip lump",
  "History",
  "Hormonal",
  "Hot shower",
  "Hotel receptionist",
  "Housework",
  "Humid",
  "Humidity",
  "Hygienist",
  "Icepacks",
  "Immune therapy",
  "Insertional",
  "Insoles",
  "Involuntary",
  "Irritate",
  "Jerky",
  "Jewellery",
  "Job",
  "Joint",
  "Junk",
  "Juvenile",
  "Keflex",
  "Kicking",
  "Lapse",
  "Largely",
  "Left heel",
  "Lemonade",
  "Life",
  "Lift weights",
  "Lifting things",
  "Limbs",
  "Limp",
  "Listless",
  "Liver oil",
  "Loneliness",
  "Long flight",
  "Long journey",
  "Long-standing",
  "Losing",
  "Loss",
  "Lotion",
  "Low energy",
  "Low-fat",
  "Lower",
  "Lunesta",
  "Malerone tablets",
  "Malignancy",
  "Manager",
  "Market researcher",
  "Massage instructor",
  "Mattress",
  "Mean",
  "Meaning",
  "Meant",
  "Measure",
  "Measurement",
  "Memory loss",
  "Memory tonic",
  "Meniere's",
  "Meniscus tear",
  "Mental illness",
  "Metoprolol",
  "Mild stroke",
  "Milk",
  "Mindfulness",
  "Mint tea",
  "Monitoring",
  "Mood swings",
  "More than 50 hours",
  "Morphine sulphate",
  "Mosquitoes",
  "Mother",
  "Mucolytic",
  "Multi organ failure",
  "Muscle",
  "Mushrooms",
  "Mx",
  "Nasal packing",
  "Nebulizer",
  "Needle biopsy",
  "Neoprene",
  "Nerve block injection",
  "Nervous",
  "Neurology",
  "Neuroma",
  "New mouse",
  "Nightmare",
  "Nose",
  "Nurse",
  "Nutrients",
  "Nutrition",
  "Obstructive apnoea",
  "Occupational consultant",
  "Oily",
  "Omega",
  "Omega-3",
  "Onion",
  "Orange juice",
  "Pack",
  "Pain",
  "Painkiller",
  "Paints",
  "Pale",
  "Palm",
  "Palmoplantar psoriasis",
  "Pancreatic",
  "Parameters",
  "Partial complex",
  "Parvovirus",
  "Patches",
  "Patchy inflamed",
  "Patient",
  "Peeling",
  "Pelvic inflammatory",
  "Pepper",
  "Physical therapy",
  "Physiotherapist",
  "Picky",
  "Piece",
  "Pitting",
  "Poisoning",
  "Polio virus",
  "Poor circulation",
  "Poor hygiene",
  "Popping head",
  "Possibly",
  "Post-nasal drip",
  "Precaution",
  "Premature ablation",
  "Present",
  "Preventive",
  "Primary",
  "Procedure",
  "Product",
  "Products",
  "Prostatic",
  "Proton pump inhibitor",
  "Proton pump inhibitors",
  "Pulmonologist",
  "Pulse",
  "Qualities",
  "Racing heart",
  "Radical hysterectomy",
  "Raynaud's",
  "Read",
  "Reading",
  "Recovery",
  "Red toe",
  "Referring",
  "Reflex",
  "Rely",
  "Remember",
  "Remembered",
  "Repetitive strain injury",
  "Replacement",
  "Research study",
  "Respiratory",
  "Restless leg",
  "Restraint",
  "Restricted",
  "Retention",
  "Retirement",
  "Rheumatic",
  "Rheumatoid arthritis",
  "Rheumatologist",
  "Rhinocort",
  "Ribs",
  "Rice",
  "Right ear",
  "Right shoulder (pain)",
  "Right thigh",
  "Right wrist",
  "Rigidity",
  "Rotator cuff tear",
  "Rubbery",
  "Rubbing",
  "Salads",
  "Scheduled",
  "School",
  "Sea",
  "Sedentary",
  "Self catheterization",
  "Senna laxatives",
  "Septic shock",
  "Septicaemia",
  "Shake",
  "Shampoo",
  "Sharp mind",
  "Shivery",
  "Shockwave",
  "Shortness of breath",
  "Shower gel",
  "Sides",
  "Sinus",
  "Sister",
  "Sites",
  "Skin biopsy",
  "Skinny",
  "Sleep",
  "Sleeping pills",
  "Slightly",
  "Sloped",
  "Small",
  "Small intestine",
  "Smoke inhalation",
  "Snoring",
  "Software",
  "Something else",
  "Spasmodic",
  "Specimen",
  "Spinal tap",
  "Sprained ankle",
  "Stamina",
  "Stationary",
  "Status epilepticus",
  "Step up",
  "Sternum",
  "Stone",
  "Stop",
  "Stumbling",
  "Sudden feeling",
  "Supplements",
  "Supraspinatus",
  "Sure",
  "Surgeon",
  "Suspected",
  "Sweats",
  "Systemic",
  "Systemic steroid",
  "Talking",
  "Tape",
  "Temporary",
  "Tenderness",
  "Tennis",
  "Text",
  "Thick mucus",
  "Thigh",
  "Thin",
  "Thinners",
  "Throat",
  "Thumbs",
  "Thump",
  "Tibia",
  "Tones",
  "Tonic clonic",
  "Torsal",
  "Tough",
  "Tour guide",
  "Tramadol injection",
  "Tunnel syndromes",
  "Twin",
  "Twinges",
  "Twisted",
  "Type 2 diabetes",
  "Uncomplicated",
  "Under 18",
  "Underactive",
  "Upstairs",
  "Urethra dilation",
  "Urgent",
  "Urinary system",
  "Venous",
  "Ventricle",
  "Very",
  "Veterinarian",
  "Vibrates",
  "Vibrating tool machine",
  "Vioxx",
  "Vitamin",
  "VNS",
  "Wait",
  "Walking",
  "Watch",
  "Water pills",
  "Waved",
  "Web",
  "Weights",
  "Whiplash accidents",
  "Whipple",
  "Whispering",
  "Wisp",
  "Withdrawal",
  "Women club",
  "Worrying",
  "Wrist splint",
  "Yoga glasses",
  "Zika",
  "Zolpidem tartrate",
  "Aqueous cream",
  "Bleeding",
  "Change germs",
  "Cracked and dry",
  "Full",
  "Gassy",
  "Hepatitis B",
  "High-fat",
  "High strung",
  "Paint factory",
  "School breaks"
];
